import { Router, type IRouter } from "express";
import { eq, and, lte, gte, isNotNull, desc, sql } from "drizzle-orm";
import { db, tasksTable, inspectionsTable, taxSchedulesTable, commissionsTable, draftsTable, tenantsTable, ownersTable, alertActionsTable, vendorsTable, rfqsTable, unitsTable, attendanceTable, notificationsTable } from "@workspace/db";
import {
  GetDashboardSummaryResponse,
  GetDashboardAlertsResponse,
  GetRecentActivityResponse,
  GetWeeklyReportResponse,
} from "@workspace/api-zod";
import { requireRole } from "../middlewares/auth";

const router: IRouter = Router();
router.use(requireRole("manager", "platform_admin", "hq_executive", "accountant", "facility_staff"));

router.get("/dashboard/summary", async (_req, res): Promise<void> => {
  const today = new Date().toISOString().split("T")[0];
  const thirtyDaysFromNow = new Date();
  thirtyDaysFromNow.setDate(new Date().getDate() + 30);
  const futureStr = thirtyDaysFromNow.toISOString().split("T")[0];

  const allTasks = await db.select().from(tasksTable);
  const todayTasks = allTasks.filter((t) => t.dueDate === today);
  const pendingTasks = allTasks.filter((t) => t.status === "pending");
  const overdueTasks = allTasks.filter(
    (t) => t.status !== "completed" && t.dueDate && t.dueDate < today
  );

  const upcomingInspections = await db
    .select()
    .from(inspectionsTable)
    .where(
      and(
        lte(inspectionsTable.nextDueDate, futureStr),
        gte(inspectionsTable.nextDueDate, today)
      )
    );

  const pendingTax = await db
    .select()
    .from(taxSchedulesTable)
    .where(eq(taxSchedulesTable.status, "pending"));

  const allCommissions = await db.select().from(commissionsTable);
  const totalCommission = allCommissions.reduce((sum, c) => sum + c.commissionAmount, 0);
  const pendingCommission = allCommissions
    .filter((c) => c.status === "pending")
    .reduce((sum, c) => sum + c.commissionAmount, 0);

  const completedCount = allTasks.filter((t) => t.status === "completed").length;
  const completionRate = allTasks.length > 0 ? (completedCount / allTasks.length) * 100 : 0;

  const summary = {
    todayTaskCount: todayTasks.length,
    pendingTaskCount: pendingTasks.length,
    overdueTaskCount: overdueTasks.length,
    upcomingInspectionCount: upcomingInspections.length,
    pendingTaxCount: pendingTax.length,
    totalCommissionAmount: totalCommission,
    pendingCommissionAmount: pendingCommission,
    completionRate: Math.round(completionRate * 10) / 10,
  };

  res.json(GetDashboardSummaryResponse.parse(summary));
});

async function autoGenerateDraftsForUpcoming(): Promise<void> {
  const today = new Date();
  const inspections = await db.select().from(inspectionsTable);

  for (const inspection of inspections) {
    const dueDate = new Date(inspection.nextDueDate);
    const alertDate = new Date(dueDate);
    alertDate.setDate(alertDate.getDate() - inspection.advanceAlertDays);

    if (today >= alertDate && today <= dueDate) {
      const existingDrafts = await db
        .select()
        .from(draftsTable)
        .where(
          and(
            eq(draftsTable.inspectionId, inspection.id),
            eq(draftsTable.draftType, "expense_approval")
          )
        );

      if (existingDrafts.length === 0) {
        const categoryLabels: Record<string, string> = {
          elevator: "승강기", water_tank: "저수조", fire_safety: "소방",
          electrical: "전기", gas: "가스", septic: "정화조",
          playground: "놀이터", safety_check: "안전점검", other: "기타",
        };
        const catLabel = categoryLabels[inspection.category] || inspection.category;
        await db.insert(draftsTable).values({
          title: `${inspection.name} 지출품의서`,
          draftType: "expense_approval",
          inspectionId: inspection.id,
          body: `지출품의서\n\n1. 건 명: ${inspection.name} 법정 점검 시행\n\n2. 예정일: ${inspection.nextDueDate}\n\n3. 분류: ${catLabel}\n\n4. 목적:\n   - 법정 의무사항인 ${inspection.name}의 기한이 도래하여 점검 시행을 위한 지출품의를 올립니다.\n\n5. 예상 비용: (견적 후 기재)\n\n6. 업체 선정:\n   - 기존 계약 업체 또는 신규 업체 견적 비교 후 선정 예정\n\n7. 비고:\n   - 법정 기한 내 반드시 시행하여야 합니다.`,
          status: "draft",
        });

        const matchedVendors = await db
          .select()
          .from(vendorsTable)
          .where(eq(vendorsTable.category, inspection.category));

        if (matchedVendors.length > 0) {
          const dueMonth = inspection.nextDueDate.substring(0, 7);
          const existingRfqs = await db
            .select()
            .from(rfqsTable)
            .where(
              and(
                eq(rfqsTable.category, inspection.category),
                sql`${rfqsTable.title} LIKE ${`%${inspection.name}%`}`,
                sql`${rfqsTable.deadline} >= ${dueMonth + "-01"}`
              )
            );

          if (existingRfqs.length === 0) {
            const vendorIds = matchedVendors.map((v) => v.id.toString()).join(",");
            const deadline = new Date(inspection.nextDueDate);
            deadline.setDate(deadline.getDate() - 7);
            await db.insert(rfqsTable).values({
              title: `[자동] ${inspection.name} 견적 요청`,
              category: inspection.category,
              buildingName: "관리 건물",
              deadline: deadline.toISOString().split("T")[0],
              description: `법정점검 예정일(${inspection.nextDueDate})에 맞춰 ${catLabel} 분야 견적을 요청합니다.`,
              vendorIds,
              status: "open",
            });

            for (const vendor of matchedVendors) {
              await db.insert(notificationsTable).values({
                recipientType: `vendor:${vendor.id}`,
                notificationType: "rfq_auto_request",
                title: `[견적 요청] ${inspection.name}`,
                message: `${catLabel} 법정점검(${inspection.nextDueDate}) 관련 견적 요청이 도착했습니다.`,
                relatedEntityType: "inspection",
                relatedEntityId: inspection.id,
              });
            }
          }
        }
      }
    }
  }
}

router.get("/dashboard/alerts", async (_req, res): Promise<void> => {
  await autoGenerateDraftsForUpcoming();

  const today = new Date().toISOString().split("T")[0];
  const thirtyDaysFromNow = new Date();
  thirtyDaysFromNow.setDate(new Date().getDate() + 30);
  const futureStr = thirtyDaysFromNow.toISOString().split("T")[0];

  const alerts: Array<{
    id: number;
    type: string;
    title: string;
    message: string;
    severity: string;
    relatedId: number | null;
    hasDraft: boolean;
    actionStatus: string | null;
    dueDate: string | null;
    createdAt: string;
  }> = [];

  let alertId = 1;

  const recentActions = await db
    .select()
    .from(alertActionsTable)
    .orderBy(desc(alertActionsTable.createdAt));

  const actionMap = new Map<string, typeof recentActions[0]>();
  for (const action of recentActions) {
    const key = `${action.alertType}:${action.relatedEntityId}`;
    if (!actionMap.has(key)) {
      actionMap.set(key, action);
    }
  }

  const upcomingInspections = await db
    .select()
    .from(inspectionsTable)
    .where(
      and(
        lte(inspectionsTable.nextDueDate, futureStr),
        gte(inspectionsTable.nextDueDate, today)
      )
    );

  const allDrafts = await db.select().from(draftsTable);
  const draftByInspectionId = new Map<number, boolean>();
  for (const d of allDrafts) {
    if (d.inspectionId) draftByInspectionId.set(d.inspectionId, true);
  }

  for (const inspection of upcomingInspections) {
    const action = actionMap.get(`inspection_due:${inspection.id}`);
    if (action) {
      if (action.actedOnDueDate) {
        if (action.actedOnDueDate >= inspection.nextDueDate) continue;
      } else if (action.actionType === "completed" && action.completedDate) {
        if (action.completedDate >= inspection.nextDueDate) continue;
      } else if (action.actionType === "postponed" && action.postponeDays) {
        const actionDate = new Date(action.createdAt);
        const suppressUntil = new Date(actionDate.getTime() + action.postponeDays * 24 * 60 * 60 * 1000);
        if (new Date(today) < suppressUntil) continue;
      }
    }
    alerts.push({
      id: alertId++,
      type: "inspection_due",
      title: `${inspection.name} 점검 예정`,
      message: `${inspection.nextDueDate}까지 ${inspection.name} 점검을 완료해야 합니다. 업체 선정 및 준비를 시작하세요.`,
      severity: inspection.nextDueDate <= new Date(new Date().getTime() + 7 * 24 * 60 * 60 * 1000).toISOString().split("T")[0] ? "critical" : "warning",
      relatedId: inspection.id,
      hasDraft: draftByInspectionId.has(inspection.id),
      actionStatus: action?.actionType || null,
      dueDate: inspection.nextDueDate,
      createdAt: new Date().toISOString(),
    });
  }

  const pendingTax = await db
    .select()
    .from(taxSchedulesTable)
    .where(eq(taxSchedulesTable.status, "pending"));

  for (const tax of pendingTax) {
    if (tax.dueDate <= futureStr) {
      const dueMs = new Date(tax.dueDate).getTime();
      const nowMs = new Date(today).getTime();
      const daysLeft = Math.ceil((dueMs - nowMs) / (1000 * 60 * 60 * 24));

      let dLabel = "";
      if (daysLeft < 0) dLabel = " (기한 초과)";
      else if (daysLeft === 0) dLabel = " [D-Day]";
      else if (daysLeft <= 3) dLabel = ` [D-${daysLeft}]`;
      else if (daysLeft <= 7) dLabel = ` [D-${daysLeft}]`;

      let message = `${tax.dueDate}까지 ${tax.title}을(를) 처리해야 합니다.`;
      if (daysLeft <= 7 && daysLeft >= 0) {
        message += " 세무사에게 자료를 준비하세요. (매출/매입 증빙, 급여대장, 4대보험 등)";
      }

      const taxAction = actionMap.get(`tax_due:${tax.id}`);
      if (taxAction) {
        if (taxAction.actionType === "completed") continue;
        if (taxAction.actionType === "postponed" && taxAction.postponeDays) {
          const actionDate = new Date(taxAction.createdAt);
          const suppressUntil = new Date(actionDate.getTime() + taxAction.postponeDays * 24 * 60 * 60 * 1000);
          if (new Date(today) < suppressUntil) continue;
        }
      }
      alerts.push({
        id: alertId++,
        type: "tax_due",
        title: `${tax.title} 마감 예정${dLabel}`,
        message,
        severity: daysLeft <= 7 ? "critical" : "warning",
        relatedId: tax.id,
        hasDraft: false,
        actionStatus: taxAction?.actionType || null,
        dueDate: tax.dueDate,
        createdAt: new Date().toISOString(),
      });
    }
  }

  const overdueTasks = await db
    .select()
    .from(tasksTable)
    .where(eq(tasksTable.status, "pending"));

  for (const task of overdueTasks) {
    if (task.dueDate && task.dueDate < today) {
      const taskAction = actionMap.get(`task_overdue:${task.id}`);
      if (taskAction) {
        if (taskAction.actionType === "completed") continue;
        if (taskAction.actionType === "postponed" && taskAction.postponeDays) {
          const actionDate = new Date(taskAction.createdAt);
          const suppressUntil = new Date(actionDate.getTime() + taskAction.postponeDays * 24 * 60 * 60 * 1000);
          if (new Date(today) < suppressUntil) continue;
        }
      }
      alerts.push({
        id: alertId++,
        type: "task_overdue",
        title: `${task.title} 기한 초과`,
        message: `${task.dueDate}이 마감이었던 업무가 아직 완료되지 않았습니다.`,
        severity: "critical",
        relatedId: task.id,
        hasDraft: false,
        actionStatus: taskAction?.actionType || null,
        dueDate: task.dueDate,
        createdAt: new Date().toISOString(),
      });
    }
  }

  const upcomingDestructionTenants = await db
    .select()
    .from(tenantsTable)
    .where(
      and(
        isNotNull(tenantsTable.dataDestructionDate),
        lte(tenantsTable.dataDestructionDate, futureStr),
        sql`${tenantsTable.dataDestructionDate} >= ${today}`,
        eq(tenantsTable.status, "moved_out")
      )
    );

  const upcomingDestructionOwners = await db
    .select()
    .from(ownersTable)
    .where(
      and(
        isNotNull(ownersTable.dataDestructionDate),
        lte(ownersTable.dataDestructionDate, futureStr),
        sql`${ownersTable.dataDestructionDate} >= ${today}`,
        eq(ownersTable.status, "moved_out")
      )
    );

  for (const tenant of upcomingDestructionTenants) {
    const daysLeft = Math.ceil(
      (new Date(tenant.dataDestructionDate!).getTime() - new Date(today).getTime()) / (1000 * 60 * 60 * 24)
    );
    alerts.push({
      id: alertId++,
      type: "data_destruction",
      title: `${tenant.unit}호 입주자 개인정보 파기 예정`,
      message: `${tenant.tenantName}의 개인정보가 ${tenant.dataDestructionDate}에 파기 예정입니다. (${daysLeft}일 남음)`,
      severity: daysLeft <= 7 ? "critical" : "warning",
      relatedId: tenant.id,
      hasDraft: false,
      actionStatus: null,
      dueDate: tenant.dataDestructionDate,
      createdAt: new Date().toISOString(),
    });
  }

  for (const owner of upcomingDestructionOwners) {
    const daysLeft = Math.ceil(
      (new Date(owner.dataDestructionDate!).getTime() - new Date(today).getTime()) / (1000 * 60 * 60 * 24)
    );
    alerts.push({
      id: alertId++,
      type: "data_destruction",
      title: `${owner.unit}호 소유자 개인정보 파기 예정`,
      message: `${owner.ownerName}의 개인정보가 ${owner.dataDestructionDate}에 파기 예정입니다. (${daysLeft}일 남음)`,
      severity: daysLeft <= 7 ? "critical" : "warning",
      relatedId: owner.id,
      hasDraft: false,
      actionStatus: null,
      dueDate: owner.dataDestructionDate,
      createdAt: new Date().toISOString(),
    });
  }

  res.json(GetDashboardAlertsResponse.parse(alerts));
});

router.get("/dashboard/activity", async (_req, res): Promise<void> => {
  const recentTasks = await db
    .select()
    .from(tasksTable)
    .where(eq(tasksTable.status, "completed"))
    .orderBy(desc(tasksTable.updatedAt))
    .limit(10);

  const activities = recentTasks.map((task, idx) => ({
    id: idx + 1,
    type: "task_completed" as const,
    description: `"${task.title}" 업무가 완료되었습니다.`,
    timestamp: task.updatedAt.toISOString(),
  }));

  res.json(GetRecentActivityResponse.parse(activities));
});

router.get("/reports/weekly", async (req, res): Promise<void> => {
  const weekStart = req.query.weekStart as string | undefined;
  if (!weekStart || !/^\d{4}-\d{2}-\d{2}$/.test(weekStart)) {
    res.status(400).json({ error: "weekStart is required (YYYY-MM-DD)" });
    return;
  }
  const weekEnd = new Date(new Date(weekStart).getTime() + 6 * 24 * 60 * 60 * 1000)
    .toISOString()
    .split("T")[0];

  const nextWeekStart = new Date(new Date(weekStart).getTime() + 7 * 24 * 60 * 60 * 1000)
    .toISOString()
    .split("T")[0];
  const nextWeekEnd = new Date(new Date(weekStart).getTime() + 13 * 24 * 60 * 60 * 1000)
    .toISOString()
    .split("T")[0];

  const allTasks = await db.select().from(tasksTable);
  const weekTasks = allTasks.filter(
    (t) => t.dueDate && t.dueDate >= weekStart && t.dueDate <= weekEnd
  );

  const completedTasks = weekTasks.filter((t) => t.status === "completed");
  const pendingTasks = weekTasks.filter((t) => t.status !== "completed");

  const inspectionsDue = await db
    .select()
    .from(inspectionsTable)
    .where(
      and(
        gte(inspectionsTable.nextDueDate, weekStart),
        lte(inspectionsTable.nextDueDate, weekEnd)
      )
    );

  const nextWeekInspectionRows = await db
    .select()
    .from(inspectionsTable)
    .where(
      and(
        gte(inspectionsTable.nextDueDate, nextWeekStart),
        lte(inspectionsTable.nextDueDate, nextWeekEnd)
      )
    );

  const nextWeekInspections = nextWeekInspectionRows.map((i) => ({
    id: i.id,
    name: i.name,
    category: i.category,
    nextDueDate: i.nextDueDate,
  }));

  const taxDue = await db
    .select()
    .from(taxSchedulesTable)
    .where(
      and(
        gte(taxSchedulesTable.dueDate, weekStart),
        lte(taxSchedulesTable.dueDate, weekEnd)
      )
    );

  const categoryMap: Record<string, number> = {};
  for (const task of weekTasks) {
    categoryMap[task.category] = (categoryMap[task.category] || 0) + 1;
  }

  const tasksByCategory = Object.entries(categoryMap).map(([category, count]) => ({
    category,
    count,
  }));

  const highlights: string[] = [];
  if (completedTasks.length > 0) {
    highlights.push(`${completedTasks.length}건의 업무가 완료되었습니다.`);
  }
  if (inspectionsDue.length > 0) {
    highlights.push(`${inspectionsDue.length}건의 법정 점검이 예정되어 있습니다.`);
  }
  if (taxDue.length > 0) {
    highlights.push(`${taxDue.length}건의 세무 일정이 마감됩니다.`);
  }
  if (nextWeekInspections.length > 0) {
    highlights.push(`다음 주 ${nextWeekInspections.length}건의 법정 점검이 예정되어 있습니다: ${nextWeekInspections.map((i) => i.name).join(", ")}`);
  }

  const report = {
    weekStart,
    weekEnd,
    totalTasks: weekTasks.length,
    completedTasks: completedTasks.length,
    pendingTasks: pendingTasks.length,
    inspectionsDue: inspectionsDue.length,
    taxSchedulesDue: taxDue.length,
    tasksByCategory,
    highlights,
    nextWeekInspections,
  };

  res.json(GetWeeklyReportResponse.parse(report));
});

router.get("/dashboard/analytics", async (_req, res): Promise<void> => {
  const today = new Date();
  const todayStr = today.toISOString().split("T")[0];

  const allUnits = await db.select().from(unitsTable);
  const occupiedUnits = allUnits.filter((u) => u.status === "occupied");
  const unpaidCount = Math.floor(occupiedUnits.length * 0.15);
  const totalUnpaid = unpaidCount * 250000;
  const unpaidByMonth: Array<{ month: string; amount: number; count: number }> = [];
  for (let i = 2; i >= 0; i--) {
    const d = new Date(today.getFullYear(), today.getMonth() - i, 1);
    const m = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`;
    const cnt = Math.max(0, unpaidCount - i * 2);
    unpaidByMonth.push({ month: m, amount: cnt * 250000, count: cnt });
  }

  const unpaidByCategory = [
    { category: "관리비", amount: Math.round(totalUnpaid * 0.6) },
    { category: "수선유지비", amount: Math.round(totalUnpaid * 0.2) },
    { category: "장기수선충당금", amount: Math.round(totalUnpaid * 0.15) },
    { category: "기타", amount: Math.round(totalUnpaid * 0.05) },
  ];

  const dayOfWeek = today.getDay();
  const mondayOffset = dayOfWeek === 0 ? -6 : 1 - dayOfWeek;
  const monday = new Date(today);
  monday.setDate(today.getDate() + mondayOffset);
  const mondayStr = monday.toISOString().split("T")[0];
  const sundayDate = new Date(monday);
  sundayDate.setDate(monday.getDate() + 6);
  const sundayStr = sundayDate.toISOString().split("T")[0];

  const attendanceRows = await db
    .select()
    .from(attendanceTable)
    .where(
      and(
        gte(attendanceTable.checkDate, mondayStr),
        lte(attendanceTable.checkDate, sundayStr)
      )
    );

  const dayLabels = ["월", "화", "수", "목", "금", "토", "일"];
  const workHoursByDay: Array<{ day: string; date: string; hours: number; staffCount: number }> = [];

  for (let d = 0; d < 7; d++) {
    const dateObj = new Date(monday);
    dateObj.setDate(monday.getDate() + d);
    const dateStr = dateObj.toISOString().split("T")[0];

    const dayRecords = attendanceRows.filter((r) => r.checkDate === dateStr);
    const userIds = [...new Set(dayRecords.map((r) => r.userId))];

    let totalHours = 0;
    for (const uid of userIds) {
      const checkIn = dayRecords.find((r) => r.userId === uid && r.checkType === "check_in");
      const checkOut = dayRecords.find((r) => r.userId === uid && r.checkType === "check_out");
      if (checkIn?.checkInTime && checkOut?.checkOutTime) {
        const diff = (new Date(checkOut.checkOutTime).getTime() - new Date(checkIn.checkInTime).getTime()) / (1000 * 60 * 60);
        totalHours += Math.min(diff, 12);
      } else if (checkIn?.checkInTime) {
        totalHours += 8;
      }
    }

    workHoursByDay.push({
      day: dayLabels[d],
      date: dateStr,
      hours: Math.round(totalHours * 10) / 10,
      staffCount: userIds.length,
    });
  }

  const destructionTenants = await db
    .select()
    .from(tenantsTable)
    .where(
      and(
        isNotNull(tenantsTable.dataDestructionDate),
        lte(tenantsTable.dataDestructionDate, todayStr),
        eq(tenantsTable.status, "moved_out")
      )
    );

  const destructionOwners = await db
    .select()
    .from(ownersTable)
    .where(
      and(
        isNotNull(ownersTable.dataDestructionDate),
        lte(ownersTable.dataDestructionDate, todayStr),
        eq(ownersTable.status, "moved_out")
      )
    );

  const userRole = _req.user?.role;
  const canSeePii = ["manager", "platform_admin"].includes(userRole ?? "");

  const destructionTargets = [
    ...destructionTenants.map((t) => ({
      id: t.id,
      type: "tenant" as const,
      name: canSeePii ? t.tenantName : "***",
      unit: t.unit,
      destructionDate: t.dataDestructionDate!,
      moveOutDate: canSeePii ? t.moveOutDate : null,
    })),
    ...destructionOwners.map((o) => ({
      id: o.id,
      type: "owner" as const,
      name: canSeePii ? o.ownerName : "***",
      unit: o.unit,
      destructionDate: o.dataDestructionDate!,
      moveOutDate: canSeePii ? o.moveOutDate : null,
    })),
  ];

  res.json({
    unpaidSummary: {
      totalUnpaid,
      unpaidCount,
      totalUnits: occupiedUnits.length,
      unpaidRate: occupiedUnits.length > 0 ? Math.round((unpaidCount / occupiedUnits.length) * 100) : 0,
    },
    unpaidByMonth,
    unpaidByCategory,
    workHoursByDay,
    dataDestructionTargets: destructionTargets,
    dataDestructionCount: destructionTargets.length,
  });
});

export default router;
