import { insertNotification } from "../lib/notificationRecipient";
import { Router, type IRouter } from "express";
import { eq, and, lte, gte, isNotNull, isNull, desc, sql, lt, inArray, ne } from "drizzle-orm";
import { db, tasksTable, inspectionsTable, taxSchedulesTable, commissionsTable, draftsTable, tenantsTable, ownersTable, alertActionsTable, vendorsTable, rfqsTable, unitsTable, attendanceTable, notificationsTable, usersTable, seasonalMaintenancePresetsTable, buildingWarrantiesTable, buildingsTable, complaintsTable, quotesTable, buildingNoticeTemplatesTable } from "@workspace/db";
import { LEGAL_PRESETS } from "./inspections";
import {
  GetDashboardSummaryResponse,
  GetDashboardAlertsResponse,
  GetRecentActivityResponse,
  GetWeeklyReportResponse,
} from "@workspace/api-zod";
import { requireRole } from "../middlewares/auth";
// [Task #221] 본사 관리 업무 템플릿을 단일 알림 소스로 통합한다.
import { resolveActiveTemplateAlerts } from "./taskTemplates";

const router: IRouter = Router();
router.use(["/dashboard","/reports"], requireRole("manager", "platform_admin", "hq_executive", "accountant", "facility_staff"));
router.get("/dashboard/summary", async (_req, res): Promise<void> => {
  const today = new Date().toISOString().split("T")[0];
  const thirtyDaysFromNow = new Date();
  thirtyDaysFromNow.setDate(new Date().getDate() + 30);
  const futureStr = thirtyDaysFromNow.toISOString().split("T")[0];

  const allTasks = await db.select().from(tasksTable);
  const todayTasks = allTasks.filter((t) => t.dueDate === today);
  const pendingTasks = allTasks.filter((t) => t.status === "pending");
  const overdueTasks = allTasks.filter(
    (t) => t.status !== "completed" && t.dueDate && t.dueDate < today
  );

  const upcomingInspections = await db
    .select()
    .from(inspectionsTable)
    .where(
      and(
        lte(inspectionsTable.nextDueDate, futureStr),
        gte(inspectionsTable.nextDueDate, today)
      )
    );

  const pendingTax = await db
    .select()
    .from(taxSchedulesTable)
    .where(eq(taxSchedulesTable.status, "pending"));

  const allCommissions = await db.select().from(commissionsTable);
  const totalCommission = allCommissions.reduce((sum, c) => sum + c.commissionAmount, 0);
  const pendingCommission = allCommissions
    .filter((c) => c.status === "pending")
    .reduce((sum, c) => sum + c.commissionAmount, 0);

  const completedCount = allTasks.filter((t) => t.status === "completed").length;
  const completionRate = allTasks.length > 0 ? (completedCount / allTasks.length) * 100 : 0;

  const summary = {
    todayTaskCount: todayTasks.length,
    pendingTaskCount: pendingTasks.length,
    overdueTaskCount: overdueTasks.length,
    upcomingInspectionCount: upcomingInspections.length,
    pendingTaxCount: pendingTax.length,
    totalCommissionAmount: totalCommission,
    pendingCommissionAmount: pendingCommission,
    completionRate: Math.round(completionRate * 10) / 10,
  };

  res.json(GetDashboardSummaryResponse.parse(summary));
});

export async function autoGenerateDraftsForUpcoming(): Promise<void> {
  const today = new Date();
  const inspections = await db.select().from(inspectionsTable);

  for (const inspection of inspections) {
    const dueDate = new Date(inspection.nextDueDate);
    const alertDate = new Date(dueDate);
    alertDate.setDate(alertDate.getDate() - inspection.advanceAlertDays);

    if (today >= alertDate && today <= dueDate) {
      const existingDrafts = await db
        .select()
        .from(draftsTable)
        .where(
          and(
            eq(draftsTable.inspectionId, inspection.id),
            eq(draftsTable.draftType, "expense_approval")
          )
        );

      if (existingDrafts.length === 0) {
        const categoryLabels: Record<string, string> = {
          elevator: "승강기", water_tank: "저수조", fire_safety: "소방",
          electrical: "전기", gas: "가스", septic: "정화조",
          playground: "놀이터", safety_check: "안전점검", other: "기타",
        };
        const catLabel = categoryLabels[inspection.category] || inspection.category;
        await db.insert(draftsTable).values({
          title: `${inspection.name} 지출품의서`,
          draftType: "expense_approval",
          inspectionId: inspection.id,
          body: `지출품의서\n\n1. 건 명: ${inspection.name} 법정 점검 시행\n\n2. 예정일: ${inspection.nextDueDate}\n\n3. 분류: ${catLabel}\n\n4. 목적:\n   - 법정 의무사항인 ${inspection.name}의 기한이 도래하여 점검 시행을 위한 지출품의를 올립니다.\n\n5. 예상 비용: (견적 후 기재)\n\n6. 업체 선정:\n   - 기존 계약 업체 또는 신규 업체 견적 비교 후 선정 예정\n\n7. 비고:\n   - 법정 기한 내 반드시 시행하여야 합니다.`,
          status: "draft",
        });

        const matchedVendors = await db
          .select()
          .from(vendorsTable)
          .where(eq(vendorsTable.category, inspection.category));

        if (matchedVendors.length > 0) {
          const dueMonth = inspection.nextDueDate.substring(0, 7);
          const existingRfqs = await db
            .select()
            .from(rfqsTable)
            .where(
              and(
                eq(rfqsTable.category, inspection.category),
                sql`${rfqsTable.title} LIKE ${`%${inspection.name}%`}`,
                sql`${rfqsTable.deadline} >= ${dueMonth + "-01"}`
              )
            );

          if (existingRfqs.length === 0) {
            const vendorIds = matchedVendors.map((v) => v.id.toString()).join(",");
            const deadline = new Date(inspection.nextDueDate);
            deadline.setDate(deadline.getDate() - 7);
            await db.insert(rfqsTable).values({
              title: `[자동] ${inspection.name} 견적 요청`,
              category: inspection.category,
              buildingName: "관리 건물",
              deadline: deadline.toISOString().split("T")[0],
              description: `법정점검 예정일(${inspection.nextDueDate})에 맞춰 ${catLabel} 분야 견적을 요청합니다.`,
              vendorIds,
              status: "open",
            });

            for (const vendor of matchedVendors) {
              await insertNotification({
                recipientType: `vendor:${vendor.id}`,
                notificationType: "rfq_auto_request",
                title: `[견적 요청] ${inspection.name}`,
                message: `${catLabel} 법정점검(${inspection.nextDueDate}) 관련 견적 요청이 도착했습니다.`,
                relatedEntityType: "inspection",
                relatedEntityId: inspection.id,
              });
            }
          }
        }
      }
    }
  }
}

router.get("/dashboard/alerts", async (req, res): Promise<void> => {

  const today = new Date().toISOString().split("T")[0];
  const thirtyDaysFromNow = new Date();
  thirtyDaysFromNow.setDate(new Date().getDate() + 30);
  const futureStr = thirtyDaysFromNow.toISOString().split("T")[0];

  // [Bugfix] 매니저/회계/시설기사는 본인 건물 데이터만 보여야 한다.
  //   기존에는 inspections/tasks/tax/tenants/owners/warranties 모두
  //   buildingId 필터 없이 전체를 끌어와 다른 건물의 (테스트업무) 항목까지
  //   필수/제안업무현황에 노출되었다(과다 생성처럼 보이는 원인).
  //   platform_admin / hq_executive 는 전체 가시성을 유지한다.
  const reqUserId = req.user?.userId ?? null;
  const reqRole = req.user?.role ?? null;
  const isGlobalRole = reqRole === "platform_admin" || reqRole === "hq_executive";
  let scopedBuildingId: number | null = null;
  if (reqUserId && reqRole && !isGlobalRole) {
    const [u] = await db
      .select({ buildingId: usersTable.buildingId })
      .from(usersTable)
      .where(eq(usersTable.id, reqUserId));
    scopedBuildingId = u?.buildingId ?? null;
  }
  const restrictByBuilding = !isGlobalRole && scopedBuildingId !== null;
  // [Security] 비-관리자(매니저/회계/시설기사 등)인데 소속 buildingId 가
  //   미할당이면 다른 건물 데이터가 새는 것을 방지하기 위해 빈 응답을 반환한다.
  if (!isGlobalRole && scopedBuildingId === null) {
    res.json([]);
    return;
  }

  const alerts: Array<{
    id: number;
    type: string;
    title: string;
    message: string;
    severity: string;
    relatedId: number | null;
    hasDraft: boolean;
    actionStatus: string | null;
    dueDate: string | null;
    penaltyInfo: string | null;
    inspectionType?: string | null;
    cycleMonths?: number | null;
    intervalDays?: number | null;
    // [Task #393] task template 알림에 미리 연결된 공고문 템플릿 ID. NULL/누락이면 CTA 미노출.
    noticeTemplateId?: number | null;
    // [Task #511] 가장 최근 액션이 scheduled 인 경우 노출되는 처리예정 메타.
    scheduledDate?: string | null;
    scheduledNotes?: string | null;
    // [Task #511] 비교견적 prefill 자동 채움용. 가장 최근 액션에 첨부된 근경/원경 사진이
    //   있으면 그 URL 을 노출, 없으면 null. /rfqs?prefill 에 그대로 전달된다.
    closeUpPhotoUrl?: string | null;
    widePhotoUrl?: string | null;
    createdAt: string;
  }> = [];

  let alertId = 1;

  const recentActions = await db
    .select()
    .from(alertActionsTable)
    .orderBy(desc(alertActionsTable.createdAt));

  // [Task #389] notice_posting 은 템플릿(=공용)이 모든 건물에 공유되므로
  //   relatedEntityId(=templateId) 만으로 키를 잡으면 다른 건물 매니저가 처리한
  //   액션이 우리 건물 알림까지 막아 cross-tenant 결함을 만든다. 행동을 건물 범위로
  //   분리하기 위해 action.userId 를 buildingId 로 매핑해 키에 포함한다.
  const actionUserIds = Array.from(
    new Set(recentActions.map((a) => a.userId).filter((id): id is number => typeof id === "number")),
  );
  const userBuildingMap = new Map<number, number | null>();
  if (actionUserIds.length > 0) {
    const usersForActions = await db
      .select({ id: usersTable.id, buildingId: usersTable.buildingId })
      .from(usersTable)
      .where(inArray(usersTable.id, actionUserIds));
    for (const u of usersForActions) {
      userBuildingMap.set(u.id, u.buildingId ?? null);
    }
  }

  const actionMap = new Map<string, typeof recentActions[0]>();
  for (const action of recentActions) {
    let key = `${action.alertType}:${action.relatedEntityId}`;
    if (action.alertType === "notice_posting") {
      const bId = action.userId != null ? userBuildingMap.get(action.userId) ?? null : null;
      key = `${action.alertType}:${action.relatedEntityId}:${bId ?? "none"}`;
    }
    if (!actionMap.has(key)) {
      actionMap.set(key, action);
    }
  }

  // [Task #511] 가장 최근 액션이 scheduled 일 때 알림에 처리예정 메타를 채워준다.
  //   actionStatus 도 "scheduled" 로 마킹해 클라이언트가 동일 알림을 다시 열었을 때
  //   "처리예정 D-N" 라벨과 모달 내부 폼 prefill 을 결정한다.
  function applyScheduledMeta(
    alert: typeof alerts[number],
    action: typeof recentActions[number] | undefined,
  ): void {
    if (action && action.actionType === "scheduled") {
      alert.scheduledDate = action.scheduledDate ?? null;
      alert.scheduledNotes = action.notes ?? null;
      alert.actionStatus = "scheduled";
    }
    // [Task #511] 액션 타입과 무관하게 가장 최근 액션에 첨부된 사진 URL 을 알림에
    //   실어 보낸다 — 비교견적 탭에서 /rfqs?prefill 로 전달되어 신규 RFQ 의 근경/원경
    //   사진 칸에 자동 채움된다. 사진이 없는 액션이면 null 그대로 둔다.
    if (action) {
      if (action.closeUpPhotoUrl) alert.closeUpPhotoUrl = action.closeUpPhotoUrl;
      if (action.widePhotoUrl) alert.widePhotoUrl = action.widePhotoUrl;
    }
  }

  const upcomingInspections = await db
    .select()
    .from(inspectionsTable)
    .where(
      and(
        lte(inspectionsTable.nextDueDate, futureStr),
        gte(inspectionsTable.nextDueDate, today),
        ...(restrictByBuilding ? [eq(inspectionsTable.buildingId, scopedBuildingId!)] : []),
      )
    );

  const allDrafts = await db.select().from(draftsTable);
  const draftByInspectionId = new Map<number, boolean>();
  for (const d of allDrafts) {
    if (d.inspectionId) draftByInspectionId.set(d.inspectionId, true);
  }

  for (const inspection of upcomingInspections) {
    const action = actionMap.get(`inspection_due:${inspection.id}`);
    if (action) {
      if (action.actedOnDueDate) {
        if (action.actedOnDueDate >= inspection.nextDueDate) continue;
      } else if (action.actionType === "completed" && action.completedDate) {
        if (action.completedDate >= inspection.nextDueDate) continue;
      } else if (action.actionType === "postponed" && action.postponeDays) {
        const actionDate = new Date(action.createdAt);
        const suppressUntil = new Date(actionDate.getTime() + action.postponeDays * 24 * 60 * 60 * 1000);
        if (new Date(today) < suppressUntil) continue;
      }
    }
    const preset = LEGAL_PRESETS.find((p) => p.name === inspection.name);
    const penaltyInfo = preset?.penaltyInfo || null;
    const inspectionAlert: typeof alerts[number] = {
      id: alertId++,
      type: "inspection_due",
      title: `${inspection.name} 점검 예정`,
      message: `${inspection.nextDueDate}까지 ${inspection.name} 점검을 완료해야 합니다. 업체 선정 및 준비를 시작하세요.`,
      severity: inspection.nextDueDate <= new Date(new Date().getTime() + 7 * 24 * 60 * 60 * 1000).toISOString().split("T")[0] ? "critical" : "warning",
      relatedId: inspection.id,
      hasDraft: draftByInspectionId.has(inspection.id),
      actionStatus: action?.actionType || null,
      dueDate: inspection.nextDueDate,
      penaltyInfo,
      inspectionType: inspection.inspectionType ?? null,
      cycleMonths: inspection.legalCycleMonths ?? null,
      intervalDays: inspection.intervalDays ?? null,
      createdAt: new Date().toISOString(),
    };
    applyScheduledMeta(inspectionAlert, action);
    alerts.push(inspectionAlert);
  }

  const overdueInspections = await db
    .select()
    .from(inspectionsTable)
    .where(
      and(
        lt(inspectionsTable.nextDueDate, today),
        ...(restrictByBuilding ? [eq(inspectionsTable.buildingId, scopedBuildingId!)] : []),
      )
    );

  for (const inspection of overdueInspections) {
    const action = actionMap.get(`inspection_due:${inspection.id}`);
    if (action) {
      if (action.actedOnDueDate) {
        if (action.actedOnDueDate >= inspection.nextDueDate) continue;
      } else if (action.actionType === "completed" && action.completedDate) {
        if (action.completedDate >= inspection.nextDueDate) continue;
      } else if (action.actionType === "postponed" && action.postponeDays) {
        const actionDate = new Date(action.createdAt);
        const suppressUntil = new Date(actionDate.getTime() + action.postponeDays * 24 * 60 * 60 * 1000);
        if (new Date(today) < suppressUntil) continue;
      }
    }
    const presetO = LEGAL_PRESETS.find((p) => p.name === inspection.name);
    const penaltyInfoO = presetO?.penaltyInfo || null;
    const daysOverdue = Math.ceil((new Date(today).getTime() - new Date(inspection.nextDueDate).getTime()) / (1000 * 60 * 60 * 24));
    const overdueInspectionAlert: typeof alerts[number] = {
      id: alertId++,
      type: "inspection_due",
      title: `${inspection.name} 기한 초과`,
      message: `${inspection.nextDueDate} 마감 기한이 ${daysOverdue}일 경과했습니다. 즉시 처리가 필요합니다.`,
      severity: "critical",
      relatedId: inspection.id,
      hasDraft: draftByInspectionId.has(inspection.id),
      actionStatus: action?.actionType || null,
      dueDate: inspection.nextDueDate,
      penaltyInfo: penaltyInfoO,
      inspectionType: inspection.inspectionType ?? null,
      cycleMonths: inspection.legalCycleMonths ?? null,
      intervalDays: inspection.intervalDays ?? null,
      createdAt: new Date().toISOString(),
    };
    applyScheduledMeta(overdueInspectionAlert, action);
    alerts.push(overdueInspectionAlert);
  }

  const pendingTax = await db
    .select()
    .from(taxSchedulesTable)
    .where(eq(taxSchedulesTable.status, "pending"));

  for (const tax of pendingTax) {
    if (tax.dueDate <= futureStr) {
      const dueMs = new Date(tax.dueDate).getTime();
      const nowMs = new Date(today).getTime();
      const daysLeft = Math.ceil((dueMs - nowMs) / (1000 * 60 * 60 * 24));

      let dLabel = "";
      if (daysLeft < 0) dLabel = " (기한 초과)";
      else if (daysLeft === 0) dLabel = " [D-Day]";
      else if (daysLeft <= 30) dLabel = ` [D-${daysLeft}]`;

      let message = `${tax.dueDate}까지 ${tax.title}을(를) 처리해야 합니다.`;
      if (daysLeft <= 30 && daysLeft >= 0) {
        message += " 세무사에게 자료를 준비하세요. (매출/매입 증빙, 급여대장, 4대보험 등)";
      }

      const taxAction = actionMap.get(`tax_due:${tax.id}`);
      if (taxAction) {
        if (taxAction.actionType === "completed") continue;
        if (taxAction.actionType === "postponed" && taxAction.postponeDays) {
          const actionDate = new Date(taxAction.createdAt);
          const suppressUntil = new Date(actionDate.getTime() + taxAction.postponeDays * 24 * 60 * 60 * 1000);
          if (new Date(today) < suppressUntil) continue;
        }
      }
      const taxAlert: typeof alerts[number] = {
        id: alertId++,
        type: "tax_due",
        title: `${tax.title} 마감 예정${dLabel}`,
        message,
        severity: daysLeft <= 30 ? "critical" : "warning",
        relatedId: tax.id,
        hasDraft: false,
        actionStatus: taxAction?.actionType || null,
        dueDate: tax.dueDate,
        penaltyInfo: null,
        createdAt: new Date().toISOString(),
      };
      applyScheduledMeta(taxAlert, taxAction);
      alerts.push(taxAlert);
    }
  }

  const overdueTasks = await db
    .select()
    .from(tasksTable)
    .where(eq(tasksTable.status, "pending"));

  // [Task #220] 후속조치에서 1회성 필수업무로 등록된 업무는 description 에
  // `__followup_source:` 마커가 들어 있다. 마감 초과가 아니더라도 필수업무현황에
  // 노출되도록 한다(동일 출처 중복 생성 방지는 작성 시점에서 검증).
  const FOLLOWUP_MARKER = "__followup_source:";

  for (const task of overdueTasks) {
    const isFollowUp = !!task.description && task.description.includes(FOLLOWUP_MARKER);
    const isOverdue = task.dueDate && task.dueDate < today;
    if (!isOverdue && !isFollowUp) continue;

    const alertType = isFollowUp ? "task_followup" : "task_overdue";
    const taskAction =
      actionMap.get(`${alertType}:${task.id}`) ?? actionMap.get(`task_overdue:${task.id}`);
    if (taskAction) {
      if (taskAction.actionType === "completed") continue;
      if (taskAction.actionType === "postponed" && taskAction.postponeDays) {
        const actionDate = new Date(taskAction.createdAt);
        const suppressUntil = new Date(actionDate.getTime() + taskAction.postponeDays * 24 * 60 * 60 * 1000);
        if (new Date(today) < suppressUntil) continue;
      }
    }
    const taskAlert: typeof alerts[number] = {
      id: alertId++,
      type: alertType,
      title: isFollowUp
        ? task.title
        : `${task.title} 기한 초과`,
      message: isFollowUp
        ? (task.description?.split("\n")[0] ?? "후속조치로 등록된 1회성 필수업무입니다.")
        : `${task.dueDate}이 마감이었던 업무가 아직 완료되지 않았습니다.`,
      severity: isOverdue ? "critical" : task.priority === "high" ? "critical" : "warning",
      relatedId: task.id,
      hasDraft: false,
      actionStatus: taskAction?.actionType || null,
      dueDate: task.dueDate,
      penaltyInfo: null,
      createdAt: new Date().toISOString(),
    };
    applyScheduledMeta(taskAlert, taskAction);
    alerts.push(taskAlert);
  }

  const upcomingDestructionTenants = await db
    .select()
    .from(tenantsTable)
    .where(
      and(
        isNotNull(tenantsTable.dataDestructionDate),
        lte(tenantsTable.dataDestructionDate, futureStr),
        sql`${tenantsTable.dataDestructionDate} >= ${today}`,
        eq(tenantsTable.status, "moved_out")
      )
    );

  const upcomingDestructionOwners = await db
    .select()
    .from(ownersTable)
    .where(
      and(
        isNotNull(ownersTable.dataDestructionDate),
        lte(ownersTable.dataDestructionDate, futureStr),
        sql`${ownersTable.dataDestructionDate} >= ${today}`,
        eq(ownersTable.status, "moved_out")
      )
    );

  for (const tenant of upcomingDestructionTenants) {
    const daysLeft = Math.ceil(
      (new Date(tenant.dataDestructionDate!).getTime() - new Date(today).getTime()) / (1000 * 60 * 60 * 24)
    );
    alerts.push({
      id: alertId++,
      type: "data_destruction",
      title: `${tenant.unit}호 입주자 개인정보 파기 예정`,
      message: `${tenant.tenantName}의 개인정보가 ${tenant.dataDestructionDate}에 파기 예정입니다. (${daysLeft}일 남음)`,
      severity: daysLeft <= 30 ? "critical" : "warning",
      relatedId: tenant.id,
      hasDraft: false,
      actionStatus: null,
      dueDate: tenant.dataDestructionDate,
      penaltyInfo: null,
      createdAt: new Date().toISOString(),
    });
  }

  for (const owner of upcomingDestructionOwners) {
    const daysLeft = Math.ceil(
      (new Date(owner.dataDestructionDate!).getTime() - new Date(today).getTime()) / (1000 * 60 * 60 * 24)
    );
    alerts.push({
      id: alertId++,
      type: "data_destruction",
      title: `${owner.unit}호 소유자 개인정보 파기 예정`,
      message: `${owner.ownerName}의 개인정보가 ${owner.dataDestructionDate}에 파기 예정입니다. (${daysLeft}일 남음)`,
      severity: daysLeft <= 30 ? "critical" : "warning",
      relatedId: owner.id,
      hasDraft: false,
      actionStatus: null,
      dueDate: owner.dataDestructionDate,
      penaltyInfo: null,
      createdAt: new Date().toISOString(),
    });
  }

  const sixtyDaysFromNow2 = new Date();
  sixtyDaysFromNow2.setDate(new Date().getDate() + 60);
  const sixtyStr2 = sixtyDaysFromNow2.toISOString().split("T")[0];

  const expiringWarranties = await db
    .select()
    .from(buildingWarrantiesTable)
    .where(
      and(
        lte(buildingWarrantiesTable.expiryDate, sixtyStr2),
        gte(buildingWarrantiesTable.expiryDate, today),
        ...(restrictByBuilding ? [eq(buildingWarrantiesTable.buildingId, scopedBuildingId!)] : []),
      )
    );

  for (const warranty of expiringWarranties) {
    const daysUntilExpiry = Math.ceil(
      (new Date(warranty.expiryDate).getTime() - new Date(today).getTime()) / (1000 * 60 * 60 * 24)
    );

    const building = await db.select().from(buildingsTable)
      .where(eq(buildingsTable.id, warranty.buildingId))
      .then(r => r[0]);

    const buildingName = building?.name || "관리 건물";

    // [Task #511] 하자담보 알림에서도 처리예정 액션을 조회해 라벨/메타를 노출한다.
    //   기존에는 action 조회를 생략해 actionStatus 가 항상 null 이었지만
    //   처리예정 통합 이후에는 모든 알림 유형에서 D-N 라벨이 필요하다.
    const warrantyAction = actionMap.get(`warranty_expiry:${warranty.id}`);
    const warrantyAlert: typeof alerts[number] = {
      id: alertId++,
      type: "warranty_expiry",
      title: `[하자담보] ${warranty.tradeName} 만료 ${daysUntilExpiry}일 전`,
      message: `${buildingName}의 ${warranty.tradeName} 하자담보가 ${warranty.expiryDate}에 만료됩니다. 하자 진단을 실시하고 필요시 시공사에 보수를 요구하세요.`,
      severity: daysUntilExpiry <= 30 ? "critical" : "warning",
      relatedId: warranty.id,
      hasDraft: false,
      actionStatus: warrantyAction?.actionType || null,
      dueDate: warranty.expiryDate,
      penaltyInfo: null,
      createdAt: new Date().toISOString(),
    };
    applyScheduledMeta(warrantyAlert, warrantyAction);
    alerts.push(warrantyAlert);
  }

  // [Task #221] 본사 관리 템플릿에서 산출된 알림을 동일한 응답에 합쳐
  // /api/dashboard/alerts 가 단일 소스로 동작하도록 한다. 사용자 컨텍스트
  // (본인 buildingId / userId) 로 scope 필터를 적용한다.
  const userId = req.user?.userId ?? null;
  let userBuildingId: number | null = null;
  if (userId) {
    const [u] = await db
      .select({ buildingId: usersTable.buildingId })
      .from(usersTable)
      .where(eq(usersTable.id, userId));
    userBuildingId = u?.buildingId ?? null;
  }
  // [Task #473] 대시보드 카드의 안내 문구·신호등 임계치는 모두 "30일" 기준이므로
  //   템플릿별 advanceAlertDays(7·14·21일짜리)에 막혀 D-13/D-18 같은 항목이 누락되지 않도록
  //   minWindowDays=30 으로 끌어올린다. advanceAlertDays 가 30일보다 큰 템플릿은
  //   기존대로 자기 윈도우를 유지한다.
  const templateAlerts = await resolveActiveTemplateAlerts(
    new Date().toISOString(),
    alertId + 1000,
    {
      userId,
      buildingId: userBuildingId,
      userRole: req.user?.role ?? null,
      minWindowDays: 30,
    },
  );
  for (const a of templateAlerts) {
    alerts.push({
      id: a.id,
      type: a.type,
      title: a.title,
      message: a.message,
      severity: a.severity,
      relatedId: a.relatedId,
      hasDraft: a.hasDraft,
      actionStatus: a.actionStatus,
      dueDate: a.dueDate,
      penaltyInfo: a.penaltyInfo,
      inspectionType: a.classification === "legal" ? "legal" : null,
      createdAt: a.createdAt,
      // [Task #393] task template 에 연결된 공고문 템플릿 ID 가 있으면 알림 응답에도 흘려보낸다.
      //   매니저앱 알림 처리 다이얼로그가 본 값을 기준으로 "공고문 작성" CTA 노출 여부를 결정한다.
      noticeTemplateId: a.noticeTemplateId,
      // [Task #511] 템플릿 알림에서도 처리예정 메타와 첨부 사진을 그대로 흘려보낸다.
      //   비교견적 탭의 prefill 동작이 다른 알림 소스와 동일하게 작동하도록 한다.
      scheduledDate: a.scheduledDate ?? null,
      scheduledNotes: a.scheduledNotes ?? null,
      closeUpPhotoUrl: a.closeUpPhotoUrl ?? null,
      widePhotoUrl: a.widePhotoUrl ?? null,
    });
  }

  // [Task #335] 견적 도착 알림: 해당 건물의 RFQ 에 제출된 미열람(submitted) 견적을
  // 필수업무현황 카드로 노출한다. 매니저가 견적을 한번이라도 보면(firstViewedAt 세팅)
  // 카드는 자동으로 사라진다. severity / dueDate 는 RFQ 마감일 기준으로 산출해
  // 마감 임박일수록 빨간 신호등이 되도록 한다. platform_admin / hq_executive 는 전체 가시성 유지.
  const pendingQuotes = await db
    .select({
      quoteId: quotesTable.id,
      vendorName: quotesTable.vendorName,
      submittedAt: quotesTable.createdAt,
      rfqTitle: rfqsTable.title,
      rfqStatus: rfqsTable.status,
      rfqBuildingId: rfqsTable.buildingId,
      rfqDeadline: rfqsTable.deadline,
    })
    .from(quotesTable)
    .innerJoin(rfqsTable, eq(quotesTable.rfqId, rfqsTable.id))
    .where(
      and(
        eq(quotesTable.status, "submitted"),
        isNull(quotesTable.firstViewedAt),
        eq(rfqsTable.status, "open"),
        // [Task #335] 만료된 RFQ 의 견적 카드는 자동 정리 (auto-close 잡 지연 시에도 잔류 방지).
        gte(rfqsTable.deadline, today),
        ...(restrictByBuilding ? [eq(rfqsTable.buildingId, scopedBuildingId!)] : []),
      ),
    );

  for (const q of pendingQuotes) {
    // RFQ 마감일까지 남은 일수 → 신호등 색. 마감일이 비어 있으면 즉시 액션 필요로 간주(critical).
    const deadlineStr = q.rfqDeadline ?? today;
    const deadlineDate = new Date(deadlineStr);
    const daysLeft = Math.floor(
      (deadlineDate.getTime() - new Date(today).getTime()) / (1000 * 60 * 60 * 24),
    );
    const severity: "critical" | "warning" | "info" =
      daysLeft <= 1 ? "critical" : daysLeft <= 3 ? "warning" : "info";
    alerts.push({
      id: alertId++,
      type: "quote_received",
      title: "견적 도착, 확인하세요",
      message: `[${q.rfqTitle}] ${q.vendorName} 업체가 견적을 제출했습니다. 즉시 확인 후 채택 여부를 결정해주세요.`,
      severity,
      relatedId: q.quoteId,
      hasDraft: false,
      actionStatus: null,
      dueDate: deadlineStr,
      penaltyInfo: null,
      createdAt: q.submittedAt?.toISOString() ?? new Date().toISOString(),
    });
  }

  // [Task #389] 공고문 게시 제안업무 — 정기 게시 스케줄이 설정된 활성 템플릿을
  // 현재 사용자의 buildingId 기준으로 평가해 leadDays 안에 들어왔으면 제안업무로 노출.
  //   - yearly: scheduleConfig = { month, day }
  //   - monthly: scheduleConfig = { day }
  //   - before_inspection: scheduleConfig = { inspectionName }
  // 노출 윈도우: today >= occurrence - leadDays && today <= occurrence (당일 포함).
  // 처리 추적은 alertActions(alertType="notice_posting", relatedEntityId=templateId,
  // actedOnDueDate=occurrenceISO) 로 동일 occurrence 기준 멱등성을 보장한다.
  // platform_admin / hq_executive 처럼 buildingId 가 비어 있는 사용자는 표시하지 않음.
  if (userBuildingId) {
    const scheduledTemplates = await db
      .select()
      .from(buildingNoticeTemplatesTable)
      .where(eq(buildingNoticeTemplatesTable.isActive, true));

    const buildingInspections = await db
      .select()
      .from(inspectionsTable)
      .where(eq(inspectionsTable.buildingId, userBuildingId));

    function pad2(n: number): string {
      return n < 10 ? `0${n}` : `${n}`;
    }
    function ymd(d: Date): string {
      return `${d.getFullYear()}-${pad2(d.getMonth() + 1)}-${pad2(d.getDate())}`;
    }
    function nextYearlyOccurrence(month: number, day: number, todayStr: string): string {
      const t = new Date(todayStr);
      let candidate = new Date(t.getFullYear(), month - 1, day);
      if (ymd(candidate) < todayStr) {
        candidate = new Date(t.getFullYear() + 1, month - 1, day);
      }
      return ymd(candidate);
    }
    function nextMonthlyOccurrence(day: number, todayStr: string): string {
      const t = new Date(todayStr);
      let candidate = new Date(t.getFullYear(), t.getMonth(), day);
      if (ymd(candidate) < todayStr) {
        candidate = new Date(t.getFullYear(), t.getMonth() + 1, day);
      }
      return ymd(candidate);
    }

    for (const tpl of scheduledTemplates) {
      if (!tpl.scheduleType || tpl.scheduleType === "none") continue;
      const cfg = (tpl.scheduleConfig as Record<string, unknown> | null) ?? null;
      let occurrence: string | null = null;
      if (tpl.scheduleType === "yearly") {
        const month = Number(cfg?.month);
        const day = Number(cfg?.day);
        if (!Number.isFinite(month) || !Number.isFinite(day) || month < 1 || month > 12 || day < 1 || day > 31) continue;
        occurrence = nextYearlyOccurrence(month, day, today);
      } else if (tpl.scheduleType === "monthly") {
        const day = Number(cfg?.day);
        if (!Number.isFinite(day) || day < 1 || day > 31) continue;
        occurrence = nextMonthlyOccurrence(day, today);
      } else if (tpl.scheduleType === "before_inspection") {
        const inspectionName = typeof cfg?.inspectionName === "string" ? cfg.inspectionName : null;
        if (!inspectionName) continue;
        // 동명 점검이 여러 개인 경우 가장 빠른 nextDueDate 사용.
        const matched = buildingInspections
          .filter((i) => i.name === inspectionName && i.nextDueDate >= today)
          .sort((a, b) => (a.nextDueDate < b.nextDueDate ? -1 : 1));
        if (matched.length === 0) continue;
        occurrence = matched[0].nextDueDate;
      }
      if (!occurrence) continue;

      const leadDays = tpl.leadDays ?? 7;
      const occMs = new Date(occurrence).getTime();
      const todayMs = new Date(today).getTime();
      const daysUntil = Math.ceil((occMs - todayMs) / (1000 * 60 * 60 * 24));
      if (daysUntil > leadDays || daysUntil < 0) continue;

      // 동일 occurrence 가 이미 처리되었으면 스킵.
      // [Task #389] 같은 템플릿이라도 건물별로 액션을 분리해 cross-building 충돌 방지.
      const action = actionMap.get(`notice_posting:${tpl.id}:${userBuildingId}`);
      if (action) {
        if (action.actedOnDueDate && action.actedOnDueDate >= occurrence) continue;
        if (action.actionType === "completed" && action.completedDate && action.completedDate >= occurrence) continue;
        if (action.actionType === "postponed" && action.postponeDays) {
          const actionDate = new Date(action.createdAt);
          const suppressUntil = new Date(actionDate.getTime() + action.postponeDays * 24 * 60 * 60 * 1000);
          if (new Date(today) < suppressUntil) continue;
        }
      }

      const dLabel = daysUntil === 0 ? " [D-Day]" : ` [D-${daysUntil}]`;
      const noticeAlert: typeof alerts[number] = {
        id: alertId++,
        type: "notice_posting",
        title: `${tpl.title} 게시 예정${dLabel}`,
        message: `${occurrence}까지 「${tpl.title}」 공지문을 입주민에게 게시해야 합니다. 처리완료를 누르면 본문이 채워진 양식이 열립니다.`,
        severity: daysUntil <= 1 ? "critical" : daysUntil <= 3 ? "warning" : "info",
        relatedId: tpl.id,
        hasDraft: false,
        actionStatus: action?.actionType || null,
        dueDate: occurrence,
        penaltyInfo: null,
        createdAt: new Date().toISOString(),
      };
      applyScheduledMeta(noticeAlert, action);
      alerts.push(noticeAlert);
    }
  }

  res.json(GetDashboardAlertsResponse.parse(alerts));
});

router.get("/dashboard/activity", async (_req, res): Promise<void> => {
  const recentTasks = await db
    .select()
    .from(tasksTable)
    .where(eq(tasksTable.status, "completed"))
    .orderBy(desc(tasksTable.updatedAt))
    .limit(10);

  const activities = recentTasks.map((task, idx) => ({
    id: idx + 1,
    type: "task_completed" as const,
    description: `"${task.title}" 업무가 완료되었습니다.`,
    timestamp: task.updatedAt.toISOString(),
  }));

  res.json(GetRecentActivityResponse.parse(activities));
});

router.get("/reports/weekly", async (req, res): Promise<void> => {
  const weekStart = req.query.weekStart as string | undefined;
  if (!weekStart || !/^\d{4}-\d{2}-\d{2}$/.test(weekStart)) {
    res.status(400).json({ error: "weekStart is required (YYYY-MM-DD)" });
    return;
  }
  const weekEnd = new Date(new Date(weekStart).getTime() + 6 * 24 * 60 * 60 * 1000)
    .toISOString()
    .split("T")[0];

  const nextWeekStart = new Date(new Date(weekStart).getTime() + 7 * 24 * 60 * 60 * 1000)
    .toISOString()
    .split("T")[0];
  const nextWeekEnd = new Date(new Date(weekStart).getTime() + 13 * 24 * 60 * 60 * 1000)
    .toISOString()
    .split("T")[0];

  const allTasks = await db.select().from(tasksTable);
  const weekTasks = allTasks.filter(
    (t) => t.dueDate && t.dueDate >= weekStart && t.dueDate <= weekEnd
  );

  const completedTasks = weekTasks.filter((t) => t.status === "completed");
  const pendingTasks = weekTasks.filter((t) => t.status !== "completed");

  const inspectionsDue = await db
    .select()
    .from(inspectionsTable)
    .where(
      and(
        gte(inspectionsTable.nextDueDate, weekStart),
        lte(inspectionsTable.nextDueDate, weekEnd)
      )
    );

  const nextWeekInspectionRows = await db
    .select()
    .from(inspectionsTable)
    .where(
      and(
        gte(inspectionsTable.nextDueDate, nextWeekStart),
        lte(inspectionsTable.nextDueDate, nextWeekEnd)
      )
    );

  const nextWeekInspections = nextWeekInspectionRows.map((i) => ({
    id: i.id,
    name: i.name,
    category: i.category,
    nextDueDate: i.nextDueDate,
  }));

  const taxDue = await db
    .select()
    .from(taxSchedulesTable)
    .where(
      and(
        gte(taxSchedulesTable.dueDate, weekStart),
        lte(taxSchedulesTable.dueDate, weekEnd)
      )
    );

  const categoryMap: Record<string, number> = {};
  for (const task of weekTasks) {
    categoryMap[task.category] = (categoryMap[task.category] || 0) + 1;
  }

  const tasksByCategory = Object.entries(categoryMap).map(([category, count]) => ({
    category,
    count,
  }));

  const allComplaints = await db.select().from(complaintsTable);
  const weekComplaints = allComplaints.filter(c => {
    const created = c.createdAt.toISOString().split("T")[0];
    return created >= weekStart && created <= weekEnd;
  });
  const completedComplaints = weekComplaints.filter(c => c.status === "completed");
  const pendingComplaints = weekComplaints.filter(c => c.status !== "completed");
  const sensitiveComplaints = weekComplaints.filter(c =>
    c.sensitivity === "sensitive" || c.sensitivity === "urgent"
  );

  const complaintSummary = {
    received: weekComplaints.length,
    completed: completedComplaints.length,
    pending: pendingComplaints.length,
    sensitiveCount: sensitiveComplaints.length,
  };

  const highlights: string[] = [];
  if (completedTasks.length > 0) {
    highlights.push(`${completedTasks.length}건의 업무가 완료되었습니다.`);
  }
  if (inspectionsDue.length > 0) {
    highlights.push(`${inspectionsDue.length}건의 법정 점검이 예정되어 있습니다.`);
  }
  if (taxDue.length > 0) {
    highlights.push(`${taxDue.length}건의 세무 일정이 마감됩니다.`);
  }
  if (nextWeekInspections.length > 0) {
    highlights.push(`다음 주 ${nextWeekInspections.length}건의 법정 점검이 예정되어 있습니다: ${nextWeekInspections.map((i) => i.name).join(", ")}`);
  }
  if (weekComplaints.length > 0) {
    highlights.push(`민원 ${weekComplaints.length}건 접수, ${completedComplaints.length}건 처리 완료, ${pendingComplaints.length}건 미처리`);
  }
  if (sensitiveComplaints.length > 0) {
    highlights.push(`민감 민원 ${sensitiveComplaints.length}건 발생`);
  }

  const report = {
    weekStart,
    weekEnd,
    totalTasks: weekTasks.length,
    completedTasks: completedTasks.length,
    pendingTasks: pendingTasks.length,
    inspectionsDue: inspectionsDue.length,
    taxSchedulesDue: taxDue.length,
    tasksByCategory,
    highlights,
    nextWeekInspections,
    complaintSummary,
  };

  res.json(GetWeeklyReportResponse.parse(report));
});

router.get("/dashboard/analytics", async (_req, res): Promise<void> => {
  const today = new Date();
  const todayStr = today.toISOString().split("T")[0];

  const userId = _req.user?.userId;
  let buildingId: number | null = null;
  if (userId) {
    const userRow = await db.select().from(usersTable).where(eq(usersTable.id, userId)).then(r => r[0]);
    buildingId = userRow?.buildingId ?? null;
  }

  const allUnits = buildingId
    ? await db.select().from(unitsTable).where(eq(unitsTable.buildingId, buildingId))
    : await db.select().from(unitsTable);
  const occupiedUnits = allUnits.filter((u) => u.status === "occupied");
  const vacantUnits = allUnits.filter((u) => u.status === "vacant");

  const totalArea = allUnits.reduce((s, u) => s + Number(u.exclusiveArea || 0), 0);
  const commonBase = 150000;
  const specialBase = 30000;
  const utilityBase = 80000;

  let totalUnpaid = 0;
  let unpaidCount = 0;
  let commonUnpaid = 0;
  let specialUnpaid = 0;
  let utilityUnpaid = 0;

  for (const unit of vacantUnits) {
    const area = Number(unit.exclusiveArea || 0);
    const ratio = area > 0 && totalArea > 0 ? area / totalArea : 1 / Math.max(allUnits.length, 1);
    const common = Math.round(commonBase * ratio);
    const special = Math.round(specialBase * ratio);
    const utility = Math.round(utilityBase * ratio);
    totalUnpaid += common + special + utility;
    commonUnpaid += common;
    specialUnpaid += special;
    utilityUnpaid += utility;
    unpaidCount++;
  }

  const unpaidByMonth: Array<{ month: string; amount: number; count: number }> = [];
  for (let i = 2; i >= 0; i--) {
    const d = new Date(today.getFullYear(), today.getMonth() - i, 1);
    const m = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`;
    unpaidByMonth.push({ month: m, amount: i === 0 ? totalUnpaid : 0, count: i === 0 ? unpaidCount : 0 });
  }

  const unpaidByCategory = [
    { category: "관리비", amount: commonUnpaid },
    { category: "수선유지비", amount: utilityUnpaid },
    { category: "장기수선충당금", amount: specialUnpaid },
    { category: "기타", amount: 0 },
  ];

  const dayOfWeek = today.getDay();
  const mondayOffset = dayOfWeek === 0 ? -6 : 1 - dayOfWeek;
  const monday = new Date(today);
  monday.setDate(today.getDate() + mondayOffset);
  const mondayStr = monday.toISOString().split("T")[0];
  const sundayDate = new Date(monday);
  sundayDate.setDate(monday.getDate() + 6);
  const sundayStr = sundayDate.toISOString().split("T")[0];

  let buildingUserIds: number[] | null = null;
  if (buildingId) {
    const buildingUsers = await db.select({ id: usersTable.id }).from(usersTable)
      .where(eq(usersTable.buildingId, buildingId));
    buildingUserIds = buildingUsers.map(u => u.id);
  }

  const allAttendance = await db
    .select()
    .from(attendanceTable)
    .where(
      and(
        gte(attendanceTable.checkDate, mondayStr),
        lte(attendanceTable.checkDate, sundayStr)
      )
    );
  const attendanceRows = buildingUserIds
    ? allAttendance.filter(a => buildingUserIds!.includes(a.userId))
    : allAttendance;

  const dayLabels = ["월", "화", "수", "목", "금", "토", "일"];
  const workHoursByDay: Array<{ day: string; date: string; hours: number; staffCount: number }> = [];

  for (let d = 0; d < 7; d++) {
    const dateObj = new Date(monday);
    dateObj.setDate(monday.getDate() + d);
    const dateStr = dateObj.toISOString().split("T")[0];

    const dayRecords = attendanceRows.filter((r) => r.checkDate === dateStr);
    const userIds = [...new Set(dayRecords.map((r) => r.userId))];

    let totalHours = 0;
    for (const uid of userIds) {
      const checkIn = dayRecords.find((r) => r.userId === uid && r.checkType === "check_in");
      const checkOut = dayRecords.find((r) => r.userId === uid && r.checkType === "check_out");
      if (checkIn?.checkInTime && checkOut?.checkOutTime) {
        const diff = (new Date(checkOut.checkOutTime).getTime() - new Date(checkIn.checkInTime).getTime()) / (1000 * 60 * 60);
        totalHours += Math.min(diff, 12);
      } else if (checkIn?.checkInTime) {
        totalHours += 8;
      }
    }

    workHoursByDay.push({
      day: dayLabels[d],
      date: dateStr,
      hours: Math.round(totalHours * 10) / 10,
      staffCount: userIds.length,
    });
  }

  const allDestructionTenants = await db
    .select()
    .from(tenantsTable)
    .where(
      and(
        isNotNull(tenantsTable.dataDestructionDate),
        lte(tenantsTable.dataDestructionDate, todayStr),
        eq(tenantsTable.status, "moved_out")
      )
    );

  const allDestructionOwners = await db
    .select()
    .from(ownersTable)
    .where(
      and(
        isNotNull(ownersTable.dataDestructionDate),
        lte(ownersTable.dataDestructionDate, todayStr),
        eq(ownersTable.status, "moved_out")
      )
    );

  let buildingUnitIds: Set<number> | null = null;
  if (buildingId) {
    const buildingUnits = await db.select({ id: unitsTable.id }).from(unitsTable)
      .where(eq(unitsTable.buildingId, buildingId));
    buildingUnitIds = new Set(buildingUnits.map(u => u.id));
  }

  const destructionTenants = buildingUnitIds
    ? allDestructionTenants.filter(t => t.unitId != null && buildingUnitIds!.has(t.unitId))
    : allDestructionTenants;

  const destructionOwners = buildingUnitIds
    ? allDestructionOwners.filter(o => o.unitId != null && buildingUnitIds!.has(o.unitId))
    : allDestructionOwners;

  const userRole = _req.user?.role;
  const canSeePii = ["manager", "platform_admin"].includes(userRole ?? "");

  const destructionTargets = [
    ...destructionTenants.map((t) => ({
      id: t.id,
      type: "tenant" as const,
      name: canSeePii ? t.tenantName : "***",
      unit: t.unit,
      destructionDate: t.dataDestructionDate!,
      moveOutDate: canSeePii ? t.moveOutDate : null,
    })),
    ...destructionOwners.map((o) => ({
      id: o.id,
      type: "owner" as const,
      name: canSeePii ? o.ownerName : "***",
      unit: o.unit,
      destructionDate: o.dataDestructionDate!,
      moveOutDate: canSeePii ? o.moveOutDate : null,
    })),
  ];

  res.json({
    unpaidSummary: {
      totalUnpaid,
      unpaidCount,
      totalUnits: allUnits.length,
      unpaidRate: allUnits.length > 0 ? Math.round((unpaidCount / allUnits.length) * 100) : 0,
    },
    unpaidByMonth,
    unpaidByCategory,
    workHoursByDay,
    dataDestructionTargets: destructionTargets,
    dataDestructionCount: destructionTargets.length,
  });
});

const SEASONAL_MAINTENANCE_DATA = [
  { month: 1, title: "혹한기 동파 방지 점검", category: "maintenance_repair", description: "배관 보온재 상태 확인, 동파 방지 열선 점검, 외부 배관 보호 조치", priority: "high", rfqCategory: "maintenance_repair" },
  { month: 2, title: "봄맞이 외벽 균열 사전 조사", category: "defect_diagnosis", description: "동절기 이후 외벽 균열, 타일 탈락 여부 사전 점검", priority: "normal", rfqCategory: "defect_diagnosis" },
  { month: 3, title: "옥상 방수층 상태 점검", category: "waterproofing", description: "우기 대비 옥상 방수층 균열·파손 점검, 드레인 청소", priority: "high", rfqCategory: "waterproofing" },
  { month: 4, title: "봄맞이 환경정비·라인마킹", category: "maintenance_repair", description: "주차장 라인마킹, 화단 정비, 외부 도장 보수, 놀이터 안전 점검", priority: "high", rfqCategory: "maintenance_repair" },
  { month: 5, title: "우기 전 방수 사전점검", category: "waterproofing", description: "옥상·외벽·지하층 방수 상태 사전 점검 및 보수 계획 수립", priority: "high", rfqCategory: "waterproofing" },
  { month: 6, title: "우기 대비 방수 긴급점검", category: "waterproofing", description: "장마 대비 옥상·지하주차장 방수 상태 긴급 점검, 배수구 정비", priority: "high", rfqCategory: "waterproofing" },
  { month: 6, title: "우기 대비 지하 침수 방지", category: "waterproofing", description: "지하주차장 누수 점검, 배수펌프 작동 확인, 방수 보수", priority: "high", rfqCategory: "waterproofing" },
  { month: 7, title: "장마 후 피해 점검 및 보수", category: "maintenance_repair", description: "장마 후 외벽·옥상·지하 피해 점검 및 긴급 보수", priority: "high", rfqCategory: "maintenance_repair" },
  { month: 8, title: "태풍 대비 시설물 점검", category: "building_maintenance", description: "태풍 대비 옥상 구조물, 간판, 창호 안전 점검", priority: "high", rfqCategory: "building_maintenance" },
  { month: 9, title: "태풍 후 외벽·창호 점검 및 보수", category: "maintenance_repair", description: "태풍 후 외벽 손상, 창호 파손, 옥상 시설물 점검 및 보수", priority: "high", rfqCategory: "maintenance_repair" },
  { month: 9, title: "하자담보 만료 사전 점검", category: "defect_diagnosis", description: "연말 하자담보 만료 예정 공종에 대한 사전 진단 실시", priority: "normal", rfqCategory: "defect_diagnosis" },
  { month: 10, title: "동절기 대비 배관 보온공사", category: "maintenance_repair", description: "배관 보온재 교체, 동파 방지 열선 설치, 외부 수전 보호", priority: "high", rfqCategory: "maintenance_repair" },
  { month: 10, title: "난방 배관 점검 및 청소", category: "mechanical", description: "난방 시즌 전 배관 청소, 보일러 점검, 순환펌프 확인", priority: "normal", rfqCategory: "mechanical" },
  { month: 11, title: "동절기 옥상 방수 마감점검", category: "waterproofing", description: "동절기 전 옥상 방수 최종 점검, 균열 보수", priority: "normal", rfqCategory: "waterproofing" },
  { month: 12, title: "연말 시설물 종합 점검", category: "building_maintenance", description: "연간 시설물 종합 점검, 차년도 영선 계획 수립", priority: "normal", rfqCategory: "building_maintenance" },
];

const SEASONAL_MAINTENANCE_REMOVED = [
  { month: 4, title: "외벽 도장 보수공사" },
];

router.get("/dashboard/seasonal-suggestions", async (req, res): Promise<void> => {
  const monthParam = req.query.month ? parseInt(req.query.month as string) : new Date().getMonth() + 1;

  for (const removed of SEASONAL_MAINTENANCE_REMOVED) {
    if (removed.month === monthParam) {
      await db.delete(seasonalMaintenancePresetsTable).where(
        and(
          eq(seasonalMaintenancePresetsTable.month, removed.month),
          eq(seasonalMaintenancePresetsTable.title, removed.title),
        ),
      );
    }
  }

  let presets = await db.select().from(seasonalMaintenancePresetsTable)
    .where(eq(seasonalMaintenancePresetsTable.month, monthParam));

  if (presets.length === 0) {
    const existingAll = await db.select().from(seasonalMaintenancePresetsTable);
    if (existingAll.length === 0) {
      await db.insert(seasonalMaintenancePresetsTable).values(SEASONAL_MAINTENANCE_DATA);
    }
    presets = await db.select().from(seasonalMaintenancePresetsTable)
      .where(eq(seasonalMaintenancePresetsTable.month, monthParam));
  }

  res.json(presets);
});

export default router;
