import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import tasksRouter from "./tasks";
import inspectionsRouter from "./inspections";
import taxSchedulesRouter from "./taxSchedules";
import vendorsRouter from "./vendors";
import commissionsRouter from "./commissions";
import dashboardRouter from "./dashboard";
import draftsRouter from "./drafts";
import tenantsRouter from "./tenants";
import ownersRouter from "./owners";
import vehiclesRouter from "./vehicles";
import notificationsRouter from "./notifications";
import documentChecklistsRouter from "./documentChecklists";
import usersRouter from "./users";
import approvalsRouter from "./approvals";
import { authMiddleware, requireRole } from "../middlewares/auth";
import rfqsRouter from "./rfqs";
import quotesRouter from "./quotes";
import workReportsRouter from "./workReports";
import settlementsRouter from "./settlements";
import safetyChecklistsRouter from "./safetyChecklists";
import maintenanceLogsRouter from "./maintenanceLogs";
import safetyTrainingsRouter from "./safetyTrainings";
import facilityDashboardRouter from "./facilityDashboard";
import approvalStepsRouter from "./approvalSteps";
import signaturesRouter from "./signatures";
import documentTemplatesRouter from "./documentTemplates";
import reportSystemRouter from "./reportSystem";
import privacyRouter from "./privacy";
import taxDeadlineChecklistsRouter from "./taxDeadlineChecklists";
import attendanceRouter from "./attendance";
import alertActionsRouter from "./alertActions";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);

router.use(authMiddleware);

router.use(vendorsRouter);
router.use(commissionsRouter);
router.use(notificationsRouter);
router.use(usersRouter);
router.use(rfqsRouter);

const buildingRouter: IRouter = Router();
const buildingOnly = requireRole("manager", "platform_admin");
buildingRouter.use(buildingOnly);
buildingRouter.use(dashboardRouter);
buildingRouter.use(approvalsRouter);
buildingRouter.use(tasksRouter);
buildingRouter.use(inspectionsRouter);
buildingRouter.use(taxSchedulesRouter);
buildingRouter.use(quotesRouter);
buildingRouter.use(workReportsRouter);
buildingRouter.use(settlementsRouter);
buildingRouter.use(draftsRouter);
buildingRouter.use(tenantsRouter);
buildingRouter.use(ownersRouter);
buildingRouter.use(vehiclesRouter);
buildingRouter.use(documentChecklistsRouter);
buildingRouter.use(approvalStepsRouter);
buildingRouter.use(signaturesRouter);
buildingRouter.use(documentTemplatesRouter);
buildingRouter.use(reportSystemRouter);
buildingRouter.use(safetyChecklistsRouter);
buildingRouter.use(maintenanceLogsRouter);
buildingRouter.use(safetyTrainingsRouter);
buildingRouter.use(facilityDashboardRouter);
buildingRouter.use(privacyRouter);
buildingRouter.use(taxDeadlineChecklistsRouter);
buildingRouter.use(attendanceRouter);
buildingRouter.use(alertActionsRouter);
router.use(buildingRouter);

export default router;
