import { eq, and, lte, gte, isNotNull, sql, desc, ne, inArray } from "drizzle-orm";
import { db, tenantsTable, ownersTable, dataDestructionLogsTable, notificationsTable, vehiclesTable, vehicleHistoryTable, dailyReportsTable, weeklySummaryReportsTable, monthlySummaryReportsTable, inspectionsTable, inspectionLogsTable, unitsTable, delinquencyActionsTable, monthlyPaymentsTable, buildingsTable, buildingNoticeTemplatesTable, usersTable, alertActionsTable, dailyJournalsTable, attendanceTable, platformSettingsTable, expenseVoucherSchedulesTable } from "@workspace/db";
import { insertNotification } from "./lib/notificationRecipient";
import { logger } from "./lib/logger";
import { autoGenerateDraftsForUpcoming } from "./routes/dashboard";
import { refundUnviewedQuotes } from "./lib/credits";
import { purgeOldUsageEvents } from "./routes/usageAnalytics";
import { publishScheduleTick } from "./lib/voucherEvents";
import { addMonths, computeRoundAmount, expectedRound } from "./lib/voucherScheduleMath";
// [Task #781] T10 외부연동 — 발송 잡 큐 워커. 스케줄러 1분 틱에서 due 잡 처리.
import { processDueJobs } from "./lib/external/adapter";

function getToday(): string {
  return new Date().toISOString().split("T")[0];
}

async function runPrivacyDestructionAlerts(): Promise<void> {
  const todayStr = getToday();
  const thirtyDaysLater = new Date();
  thirtyDaysLater.setDate(thirtyDaysLater.getDate() + 30);
  const thirtyDaysStr = thirtyDaysLater.toISOString().split("T")[0];

  const existingAlerts = await db
    .select()
    .from(notificationsTable)
    .where(
      and(
        eq(notificationsTable.notificationType, "data_destruction_alert"),
        gte(notificationsTable.createdAt, new Date(todayStr))
      )
    );

  if (existingAlerts.length > 0) {
    logger.info("Privacy destruction alert already sent today, skipping");
    return;
  }

  const upcomingTenants = await db
    .select()
    .from(tenantsTable)
    .where(
      and(
        isNotNull(tenantsTable.dataDestructionDate),
        lte(tenantsTable.dataDestructionDate, thirtyDaysStr),
        sql`${tenantsTable.dataDestructionDate} > ${todayStr}`,
        eq(tenantsTable.status, "moved_out")
      )
    );

  const upcomingOwners = await db
    .select()
    .from(ownersTable)
    .where(
      and(
        isNotNull(ownersTable.dataDestructionDate),
        lte(ownersTable.dataDestructionDate, thirtyDaysStr),
        sql`${ownersTable.dataDestructionDate} > ${todayStr}`,
        eq(ownersTable.status, "moved_out")
      )
    );

  const totalCount = upcomingTenants.length + upcomingOwners.length;

  if (totalCount > 0) {
    const details = [
      ...upcomingTenants.map((t) => `입주자 ${t.unit}호 ${t.tenantName} (${t.dataDestructionDate})`),
      ...upcomingOwners.map((o) => `소유자 ${o.unit}호 ${o.ownerName} (${o.dataDestructionDate})`),
    ].join(", ");

    await insertNotification({
      recipientType: "admin",
      notificationType: "data_destruction_alert",
      title: "개인정보 파기 예정 알림",
      message: `30일 이내 파기 예정: ${totalCount}건 - ${details}`,
      relatedEntityType: "privacy",
    });

    logger.info({ count: totalCount }, "Privacy destruction alert created");
  }
}

async function runPrivacyDestructionProcessing(): Promise<void> {
  const todayStr = getToday();

  const dueTenants = await db
    .select()
    .from(tenantsTable)
    .where(
      and(
        isNotNull(tenantsTable.dataDestructionDate),
        lte(tenantsTable.dataDestructionDate, todayStr),
        eq(tenantsTable.status, "moved_out")
      )
    );

  const dueOwners = await db
    .select()
    .from(ownersTable)
    .where(
      and(
        isNotNull(ownersTable.dataDestructionDate),
        lte(ownersTable.dataDestructionDate, todayStr),
        eq(ownersTable.status, "moved_out")
      )
    );

  let processedCount = 0;

  for (const tenant of dueTenants) {
    await db.insert(dataDestructionLogsTable).values({
      entityType: "tenant",
      entityId: tenant.id,
      unit: tenant.unit,
      originalName: tenant.tenantName,
      destructionType: "anonymization",
      processedBy: "system",
      notes: `자동 파기 - 퇴거일: ${tenant.moveOutDate}, 파기예정일: ${tenant.dataDestructionDate}`,
    });

    await db
      .update(tenantsTable)
      .set({
        tenantName: "***",
        residentId: null,
        phone: null,
        emergencyContact: null,
        email: null,
        registeredAddress: null,
        guarantorName: null,
        guarantorPhone: null,
        guarantorRelation: null,
        notes: "[개인정보 자동 파기 처리됨]",
        status: "destroyed",
      })
      .where(eq(tenantsTable.id, tenant.id));

    processedCount++;
  }

  for (const owner of dueOwners) {
    await db.insert(dataDestructionLogsTable).values({
      entityType: "owner",
      entityId: owner.id,
      unit: owner.unit,
      originalName: owner.ownerName,
      destructionType: "anonymization",
      processedBy: "system",
      notes: `자동 파기 - 퇴거일: ${owner.moveOutDate}, 파기예정일: ${owner.dataDestructionDate}`,
    });

    await db
      .update(ownersTable)
      .set({
        ownerName: "***",
        phone: null,
        email: null,
        registeredAddress: null,
        notes: "[개인정보 자동 파기 처리됨]",
        status: "destroyed",
      })
      .where(eq(ownersTable.id, owner.id));

    processedCount++;
  }

  if (processedCount > 0) {
    await insertNotification({
      recipientType: "admin",
      notificationType: "data_destruction_completed",
      title: "개인정보 자동 파기 처리 완료",
      message: `${processedCount}건의 개인정보가 자동 파기(익명화) 처리되었습니다.`,
      relatedEntityType: "privacy",
    });

    logger.info({ count: processedCount }, "Privacy data auto-destroyed");
  }
}

async function runVehicleMonthlyInspection(): Promise<void> {
  const now = new Date();
  const monthStart = new Date(now.getFullYear(), now.getMonth(), 1);

  const existingInspection = await db
    .select()
    .from(notificationsTable)
    .where(
      and(
        eq(notificationsTable.notificationType, "vehicle_monthly_inspection"),
        gte(notificationsTable.createdAt, monthStart)
      )
    );

  if (existingInspection.length > 0) {
    logger.info("Vehicle monthly inspection already run this month, skipping");
    return;
  }

  const allVehicles = await db
    .select()
    .from(vehiclesTable)
    .where(eq(vehiclesTable.status, "registered"));

  const registeredUnits = new Set(allVehicles.map((v) => v.unit));

  const allTenants = await db
    .select({ unit: tenantsTable.unit, tenantName: tenantsTable.tenantName })
    .from(tenantsTable)
    .where(eq(tenantsTable.status, "active"));

  const unregisteredUnits = allTenants.filter((t) => !registeredUnits.has(t.unit));

  if (unregisteredUnits.length > 0) {
    const unitList = unregisteredUnits
      .slice(0, 10)
      .map((u) => `${u.unit}호`)
      .join(", ");
    const suffix = unregisteredUnits.length > 10 ? ` 외 ${unregisteredUnits.length - 10}건` : "";

    await insertNotification({
      recipientType: "admin",
      notificationType: "vehicle_monthly_inspection",
      title: "월별 차량 점검 알림",
      message: `미등록 차량 ${unregisteredUnits.length}건 확인 필요: ${unitList}${suffix}`,
      relatedEntityType: "vehicle",
    });

    logger.info({ count: unregisteredUnits.length }, "Vehicle monthly inspection alert created");
  }
}

async function runWeeklyReportAutoGeneration(): Promise<void> {
  const today = new Date();
  const dayOfWeek = today.getDay();
  if (dayOfWeek !== 1) return;

  const mondayStr = today.toISOString().split("T")[0];
  const lastSunday = new Date(today);
  lastSunday.setDate(today.getDate() - 1);
  const lastSundayStr = lastSunday.toISOString().split("T")[0];
  const lastMonday = new Date(today);
  lastMonday.setDate(today.getDate() - 7);
  const lastMondayStr = lastMonday.toISOString().split("T")[0];

  const existing = await db.select().from(weeklySummaryReportsTable)
    .where(eq(weeklySummaryReportsTable.weekStart, lastMondayStr));
  if (existing.length > 0) {
    logger.info("Weekly report already exists for this week, skipping");
    return;
  }

  const dailyReports = await db.select().from(dailyReportsTable)
    .where(and(
      gte(dailyReportsTable.reportDate, lastMondayStr),
      lte(dailyReportsTable.reportDate, lastSundayStr)
    ));

  const typeLabel: Record<string, string> = {
    expense: "경비", cleaning: "미화", maintenance: "유지보수",
    security: "보안", other: "기타",
  };
  const typeCount: Record<string, number> = {};
  for (const dr of dailyReports) {
    const label = typeLabel[dr.reportType] || dr.reportType;
    typeCount[label] = (typeCount[label] || 0) + 1;
  }

  const allInspections = await db.select().from(inspectionsTable);
  const weekInspDue = allInspections.filter(
    (i) => i.nextDueDate >= lastMondayStr && i.nextDueDate <= lastSundayStr
  );
  const allLogs = await db.select().from(inspectionLogsTable);
  const weekLogs = allLogs.filter(
    (l) => l.inspectionDate >= lastMondayStr && l.inspectionDate <= lastSundayStr
  );

  let inspSection = "";
  if (weekInspDue.length > 0 || weekLogs.length > 0) {
    inspSection = "\n\n■ 금주 점검 현황";
    if (weekLogs.length > 0) {
      inspSection += `\n  완료된 점검: ${weekLogs.length}건`;
    }
    const pending = weekInspDue.filter(
      (i) => !weekLogs.some((l) => l.inspectionId === i.id)
    );
    if (pending.length > 0) {
      inspSection += `\n  미완료 점검: ${pending.length}건`;
    }
  }

  const summary = `[자동 생성] 주간 보고 요약 (${lastMondayStr} ~ ${lastSundayStr})\n\n총 ${dailyReports.length}건의 일간 보고서\n${Object.entries(typeCount).map(([t, c]) => `${t}: ${c}건`).join("\n")}\n\n${dailyReports.map((dr) => `- [${dr.reportDate}] ${dr.title}`).join("\n")}${inspSection}`;

  await db.insert(weeklySummaryReportsTable).values({
    title: `[자동] ${lastMondayStr} 주간 보고`,
    weekStart: lastMondayStr,
    weekEnd: lastSundayStr,
    summary,
    totalDailyReports: dailyReports.length,
    dailyReportIds: dailyReports.map((d) => d.id).join(","),
    authorId: 0,
    authorName: "시스템",
    status: "draft",
  });

  logger.info({ weekStart: lastMondayStr, dailyCount: dailyReports.length }, "Auto-generated weekly report");
}

async function computeBuildingAccountingData(buildingId: number, reportMonth: string) {
  const buildingUnits = await db.select().from(unitsTable)
    .where(eq(unitsTable.buildingId, buildingId));
  const unitIds = new Set(buildingUnits.map(u => u.id));
  const unitCount = buildingUnits.length;

  const allBilling = await db.select().from(monthlyPaymentsTable)
    .where(eq(monthlyPaymentsTable.billingMonth, reportMonth));
  const billingRecords = allBilling.filter(r => unitIds.has(r.unitId));

  let totalBilled = 0, totalCollected = 0, unpaidCount = 0, unpaidAmount = 0;
  if (billingRecords.length > 0) {
    totalBilled = billingRecords.reduce((s, r) => s + r.totalAmount, 0);
    totalCollected = billingRecords.reduce((s, r) => s + r.paidAmount, 0);
    unpaidCount = billingRecords.filter(r => !r.isPaid).length;
    unpaidAmount = Math.round(totalBilled - totalCollected);
  }
  const collectionRate = totalBilled > 0 ? Math.round((totalCollected / totalBilled) * 1000) / 10 : 0;

  const prevMonthDate = new Date(parseInt(reportMonth.split("-")[0]), parseInt(reportMonth.split("-")[1]) - 2, 1);
  const prevMonth = `${prevMonthDate.getFullYear()}-${String(prevMonthDate.getMonth() + 1).padStart(2, "0")}`;
  const allPrevBilling = await db.select().from(monthlyPaymentsTable)
    .where(eq(monthlyPaymentsTable.billingMonth, prevMonth));
  const prevBillingRecords = allPrevBilling.filter(r => unitIds.has(r.unitId));

  let momChangePct: number | null = null;
  if (prevBillingRecords.length > 0) {
    const prevTotal = prevBillingRecords.reduce((s, r) => s + r.totalAmount, 0);
    if (prevTotal > 0) {
      momChangePct = Math.round(((totalBilled - prevTotal) / prevTotal) * 1000) / 10;
    }
  }

  const allTenants = await db.select().from(tenantsTable);
  const occupantCardCount = allTenants.filter(t => t.unitId && unitIds.has(t.unitId) && t.status === "active").length;

  const allVehicles = await db.select().from(vehiclesTable);
  const vehicleCardCount = allVehicles.filter(v => v.buildingId === buildingId && v.status === "registered").length;

  return { totalBilled, totalCollected, collectionRate, unpaidAmount, unpaidCount, momChangePct, occupantCardCount, vehicleCardCount, unitCount };
}

async function runMonthlyReportAutoGeneration(): Promise<void> {
  const today = new Date();
  const dayOfWeek = today.getDay();
  if (dayOfWeek !== 1 || today.getDate() > 7) return;

  const lastMonth = new Date(today.getFullYear(), today.getMonth() - 1, 1);
  const reportMonth = `${lastMonth.getFullYear()}-${String(lastMonth.getMonth() + 1).padStart(2, "0")}`;

  const existing = await db.select().from(monthlySummaryReportsTable)
    .where(eq(monthlySummaryReportsTable.reportMonth, reportMonth));

  const weeklyReports = await db.select().from(weeklySummaryReportsTable)
    .where(sql`${weeklySummaryReportsTable.weekStart} LIKE ${reportMonth + "%"}`);

  const totalDailyCount = weeklyReports.reduce((s, r) => s + r.totalDailyReports, 0);

  const monthStart = `${reportMonth}-01`;
  const monthEndDate = new Date(parseInt(reportMonth.split("-")[0]), parseInt(reportMonth.split("-")[1]), 0);
  const monthEnd = monthEndDate.toISOString().split("T")[0];

  const allLogs = await db.select().from(inspectionLogsTable);
  const monthLogs = allLogs.filter(
    (l) => l.inspectionDate >= monthStart && l.inspectionDate <= monthEnd
  );

  let inspSummary = "";
  if (monthLogs.length > 0) {
    const resultCounts: Record<string, number> = {};
    for (const l of monthLogs) {
      resultCounts[l.result] = (resultCounts[l.result] || 0) + 1;
    }
    inspSummary = `\n\n■ 월간 점검 현황\n  완료: ${monthLogs.length}건\n  결과: ${Object.entries(resultCounts).map(([r, c]) => `${r} ${c}건`).join(", ")}`;
  }

  const buildings = await db.select().from(buildingsTable);

  for (const building of buildings) {
    const existingForBuilding = existing.find(e => e.buildingId === building.id);
    if (existingForBuilding) continue;

    const acct = await computeBuildingAccountingData(building.id, reportMonth);

    let accountingSummary = "";
    if (acct.totalBilled > 0) {
      const paidCount = acct.unitCount - acct.unpaidCount;
      let momChange = "";
      if (acct.momChangePct !== null) {
        const arrow = acct.momChangePct > 0 ? "▲" : acct.momChangePct < 0 ? "▼" : "→";
        momChange = `\n  전월 대비: ${arrow} ${acct.momChangePct > 0 ? "+" : ""}${acct.momChangePct}%`;
      }
      accountingSummary = `\n\n■ 회계 현황\n  부과 총액: ₩${Math.round(acct.totalBilled).toLocaleString()}\n  수납 총액: ₩${Math.round(acct.totalCollected).toLocaleString()}\n  수납률: ${acct.collectionRate}% (${paidCount}/${acct.unitCount}세대)\n  미납 세대: ${acct.unpaidCount}세대 (₩${acct.unpaidAmount.toLocaleString()})${momChange}`;
    }

    const summary = `[자동 생성] 월간 보고 요약 (${reportMonth}) - ${building.name}\n\n총 ${weeklyReports.length}건의 주간 보고서\n총 ${totalDailyCount}건의 일간 보고서 집계\n\n${weeklyReports.map((wr) => `- ${wr.title} (일간 보고 ${wr.totalDailyReports}건)`).join("\n")}${inspSummary}${accountingSummary}\n\n■ 현황 지표\n  입주자카드 작성: ${acct.occupantCardCount}/${acct.unitCount}세대\n  차량 등록: ${acct.vehicleCardCount}대`;

    await db.insert(monthlySummaryReportsTable).values({
      title: `[자동] ${reportMonth} 월간 보고 - ${building.name}`,
      reportMonth,
      buildingId: building.id,
      summary,
      totalWeeklyReports: weeklyReports.length,
      weeklyReportIds: weeklyReports.map((w) => w.id).join(","),
      totalBilled: acct.totalBilled,
      totalCollected: acct.totalCollected,
      collectionRate: acct.collectionRate,
      unpaidAmount: acct.unpaidAmount,
      unpaidUnits: acct.unpaidCount,
      occupantCardCount: acct.occupantCardCount,
      totalUnits: acct.unitCount,
      vehicleCardCount: acct.vehicleCardCount,
      momChangePct: acct.momChangePct,
      authorId: 0,
      authorName: "시스템",
      status: "draft",
    });

    logger.info({ reportMonth, buildingId: building.id, buildingName: building.name }, "Auto-generated monthly report for building");
  }
}

async function computeUnitBillingStatus(unitId: number): Promise<{ overdueMonths: number; totalOverdueAmount: number } | null> {
  const now = new Date();
  const cutoffDate = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-25`;

  const unpaidRecords = await db.select().from(monthlyPaymentsTable)
    .where(
      and(
        eq(monthlyPaymentsTable.unitId, unitId),
        eq(monthlyPaymentsTable.isPaid, false),
        lte(monthlyPaymentsTable.dueDate, cutoffDate)
      )
    );

  if (unpaidRecords.length < 2) return null;

  const totalOverdueAmount = unpaidRecords.reduce((sum, r) => sum + (r.totalAmount - r.paidAmount), 0);

  return {
    overdueMonths: unpaidRecords.length,
    totalOverdueAmount: Math.round(totalOverdueAmount),
  };
}

async function runDelinquencyDetection(): Promise<void> {
  const todayStr = getToday();

  const existingCheck = await db
    .select()
    .from(notificationsTable)
    .where(
      and(
        eq(notificationsTable.notificationType, "delinquency_detection"),
        gte(notificationsTable.createdAt, new Date(todayStr))
      )
    );

  if (existingCheck.length > 0) {
    logger.info("Delinquency detection already run today, skipping");
    return;
  }

  const allUnits = await db.select().from(unitsTable)
    .where(eq(unitsTable.status, "occupied"));

  if (allUnits.length === 0) return;

  const allTenants = await db.select().from(tenantsTable)
    .where(eq(tenantsTable.status, "active"));

  const tenantByUnit = new Map<number, typeof allTenants[0]>();
  for (const t of allTenants) {
    if (t.unitId) tenantByUnit.set(t.unitId, t);
  }

  const existingActive = await db.select().from(delinquencyActionsTable)
    .where(eq(delinquencyActionsTable.status, "active"));
  const activeUnitIds = new Set(existingActive.map(a => a.unitId));

  let detectedCount = 0;

  for (const unit of allUnits) {
    if (activeUnitIds.has(unit.id)) continue;

    const billing = await computeUnitBillingStatus(unit.id);
    if (!billing) continue;

    const tenant = tenantByUnit.get(unit.id);

    await db.insert(delinquencyActionsTable).values({
      unitId: unit.id,
      unitNumber: unit.unitNumber,
      tenantId: tenant?.id ?? null,
      tenantName: tenant?.tenantName ?? null,
      overdueMonths: billing.overdueMonths,
      totalOverdueAmount: billing.totalOverdueAmount,
      actionType: "detected",
      status: "active",
      performedBy: "system",
      notes: `[${todayStr}] 자동 감지: ${billing.overdueMonths}개월 연체, 미납액 ${billing.totalOverdueAmount.toLocaleString()}원`,
    });

    detectedCount++;
  }

  if (detectedCount > 0) {
    await insertNotification({
      recipientType: "admin",
      notificationType: "delinquency_detection",
      title: "연체 세대 자동 감지",
      message: `${detectedCount}건의 2개월 이상 연체 세대가 감지되었습니다. 연체 관리에서 확인하세요.`,
      relatedEntityType: "delinquency",
    });

    logger.info({ count: detectedCount }, "Delinquency detection completed");
  }
}

async function runDelinquencyAutoResolution(): Promise<void> {
  const todayStr = getToday();

  const activeActions = await db.select().from(delinquencyActionsTable)
    .where(eq(delinquencyActionsTable.status, "active"));

  if (activeActions.length === 0) return;

  let resolvedCount = 0;

  for (const action of activeActions) {
    if (!action.unitId) continue;

    const [unit] = await db.select().from(unitsTable)
      .where(eq(unitsTable.id, action.unitId));
    if (!unit) continue;

    const billing = await computeUnitBillingStatus(unit.id);

    if (billing) continue;

    if (action.actionType === "parking_suspended") {
      const suspendedVehicles = await db.select().from(vehiclesTable)
        .where(and(
          eq(vehiclesTable.unit, action.unitNumber),
          eq(vehiclesTable.buildingId, unit.buildingId),
          eq(vehiclesTable.status, "suspended")
        ));

      for (const v of suspendedVehicles) {
        await db.update(vehiclesTable)
          .set({ status: "registered" })
          .where(eq(vehiclesTable.id, v.id));

        await db.insert(vehicleHistoryTable).values({
          vehicleId: v.id,
          action: "reactivated",
          vehicleNumber: v.vehicleNumber,
          unit: v.unit,
          performedBy: "system",
          notes: "연체 해소 자동 감지로 주차권 복원",
        });
      }
    }

    await db.update(delinquencyActionsTable)
      .set({
        status: "resolved",
        resolvedDate: new Date(),
        notes: `${action.notes ? action.notes + "\n" : ""}[${todayStr}] 자동 해소: 미납 해소 감지`,
      })
      .where(eq(delinquencyActionsTable.id, action.id));

    resolvedCount++;
  }

  if (resolvedCount > 0) {
    await insertNotification({
      recipientType: "admin",
      notificationType: "delinquency_auto_resolved",
      title: "연체 자동 해소",
      message: `${resolvedCount}건의 연체가 수납 확인으로 자동 해소되었습니다.`,
      relatedEntityType: "delinquency",
    });

    logger.info({ count: resolvedCount }, "Delinquency auto-resolution completed");
  }
}

// [Task #389] 공고문 게시 제안업무 자동화 — 정기 게시 스케줄이 설정된 공지 템플릿을
//   매니저 별 buildingId 기준으로 평가해 발생일 leadDays 이전부터 매니저 dashboard
//   "제안업무"에 노출되는 알림(notifications) 을 멱등하게 생성한다.
//   - 같은 (template, building, occurrence) 조합 알림이 이미 만들어져 있으면 다시
//     만들지 않는다 (relatedEntityType="building_notice_template",
//     relatedEntityId=templateId 의 message 안에 occurrence 문자열을 포함시켜 식별).
//   - 매니저 대시보드 화면 자체는 이미 dashboard.ts 가 같은 규칙으로 즉시 알림을
//     생성하므로, 이 잡은 알림함(notifications) 행을 채워 추후 푸시/메일 트리거의
//     싱글 소스로 활용하기 위한 백업 기록이다.
async function runNoticePostingSuggestion(): Promise<void> {
  const todayStr = getToday();
  const today = new Date(todayStr);

  const activeTemplates = await db
    .select()
    .from(buildingNoticeTemplatesTable)
    .where(eq(buildingNoticeTemplatesTable.isActive, true));
  const scheduled = activeTemplates.filter(
    (t) => t.scheduleType && t.scheduleType !== "none",
  );
  if (scheduled.length === 0) return;

  // 알림 대상 건물: 활성 매니저(또는 회계/시설)가 소속된 건물만 대상.
  const staff = await db
    .select({ id: usersTable.id, buildingId: usersTable.buildingId })
    .from(usersTable);
  const buildingIds = Array.from(
    new Set(staff.map((s) => s.buildingId).filter((id): id is number => typeof id === "number")),
  );
  if (buildingIds.length === 0) return;
  // userId → buildingId 맵: alertActions 가 building 컬럼을 갖지 않으므로
  // 처리완료된 액션의 owner user 를 통해 건물을 식별한다 (멱등 dedupe 용).
  const userBuildingMap = new Map<number, number | null>();
  for (const u of staff) {
    userBuildingMap.set(u.id, u.buildingId ?? null);
  }

  function pad2(n: number): string {
    return n < 10 ? `0${n}` : `${n}`;
  }
  function ymd(d: Date): string {
    return `${d.getFullYear()}-${pad2(d.getMonth() + 1)}-${pad2(d.getDate())}`;
  }
  function nextYearlyOccurrence(month: number, day: number): string {
    let candidate = new Date(today.getFullYear(), month - 1, day);
    if (ymd(candidate) < todayStr) {
      candidate = new Date(today.getFullYear() + 1, month - 1, day);
    }
    return ymd(candidate);
  }
  function nextMonthlyOccurrence(day: number): string {
    let candidate = new Date(today.getFullYear(), today.getMonth(), day);
    if (ymd(candidate) < todayStr) {
      candidate = new Date(today.getFullYear(), today.getMonth() + 1, day);
    }
    return ymd(candidate);
  }

  let createdCount = 0;
  for (const tpl of scheduled) {
    const cfg = (tpl.scheduleConfig as Record<string, unknown> | null) ?? null;
    for (const buildingId of buildingIds) {
      let occurrence: string | null = null;
      if (tpl.scheduleType === "yearly") {
        const month = Number(cfg?.month);
        const day = Number(cfg?.day);
        if (!Number.isFinite(month) || !Number.isFinite(day)) continue;
        occurrence = nextYearlyOccurrence(month, day);
      } else if (tpl.scheduleType === "monthly") {
        const day = Number(cfg?.day);
        if (!Number.isFinite(day)) continue;
        occurrence = nextMonthlyOccurrence(day);
      } else if (tpl.scheduleType === "before_inspection") {
        const inspectionName = typeof cfg?.inspectionName === "string" ? cfg.inspectionName : null;
        if (!inspectionName) continue;
        const matched = await db
          .select()
          .from(inspectionsTable)
          .where(and(eq(inspectionsTable.buildingId, buildingId), eq(inspectionsTable.name, inspectionName)));
        const upcoming = matched
          .filter((i) => i.nextDueDate >= todayStr)
          .sort((a, b) => (a.nextDueDate < b.nextDueDate ? -1 : 1));
        if (upcoming.length === 0) continue;
        occurrence = upcoming[0].nextDueDate;
      }
      if (!occurrence) continue;

      const leadDays = tpl.leadDays ?? 7;
      const occMs = new Date(occurrence).getTime();
      const todayMs = today.getTime();
      const daysUntil = Math.ceil((occMs - todayMs) / (1000 * 60 * 60 * 24));
      if (daysUntil > leadDays || daysUntil < 0) continue;

      // 멱등 체크 1: 동일 (template, building, occurrence) 알림이 이미 있는지.
      const existing = await db
        .select()
        .from(notificationsTable)
        .where(
          and(
            eq(notificationsTable.notificationType, "notice_posting_suggestion"),
            eq(notificationsTable.relatedEntityType, "building_notice_template"),
            eq(notificationsTable.relatedEntityId, tpl.id),
          ),
        );
      const tag = `B${buildingId}@${occurrence}`;
      if (existing.some((n) => n.message.includes(tag))) continue;

      // 멱등 체크 2: 같은 occurrence 가 이미 처리완료/연기됐다면 (해당 건물의
      // 매니저가 누른 alertActions 가 존재) 알림 행 자체를 만들지 않는다.
      const acted = await db
        .select()
        .from(alertActionsTable)
        .where(
          and(
            eq(alertActionsTable.alertType, "notice_posting"),
            eq(alertActionsTable.relatedEntityType, "building_notice_template"),
            eq(alertActionsTable.relatedEntityId, tpl.id),
          ),
        );
      const suppressed = acted.some((a) => {
        const actionBuilding = a.userId != null ? userBuildingMap.get(a.userId) ?? null : null;
        if (actionBuilding !== buildingId) return false;
        if (a.actedOnDueDate && a.actedOnDueDate >= occurrence!) return true;
        if (a.actionType === "completed" && a.completedDate && a.completedDate >= occurrence!) return true;
        if (a.actionType === "postponed" && a.postponeDays) {
          const actionDate = new Date(a.createdAt);
          const suppressUntil = new Date(actionDate.getTime() + a.postponeDays * 24 * 60 * 60 * 1000);
          if (today < suppressUntil) return true;
        }
        return false;
      });
      if (suppressed) continue;

      await insertNotification({
        recipientType: "admin",
        notificationType: "notice_posting_suggestion",
        title: `${tpl.title} 게시 예정`,
        message: `${tag} ${occurrence}까지 「${tpl.title}」 공지문 게시가 필요합니다 (D-${daysUntil}).`,
        relatedEntityType: "building_notice_template",
        relatedEntityId: tpl.id,
      });
      createdCount++;
    }
  }
  if (createdCount > 0) {
    logger.info({ count: createdCount }, "Notice posting suggestions created");
  }
}

// ---------------------------------------------------------------------------
// [Task #609] 일보 작성 독려 알림 (소프트 리마인더, 본인만)
// ---------------------------------------------------------------------------
// 매일 KST 기준 저녁(기본 18:00) / 다음날 오전(기본 09:30) 한 번씩,
// 당일 일보를 아직 작성하지 않은 본인에게만 알림 종에 부드러운 안내를 띄운다.
//
// 핵심 보장:
//   - 본인에게만 (recipientType="user:<id>"). 상사/본사/오픈채팅으로 절대 에스컬레이션 X.
//   - (user, date, type) 조합당 최대 1회. notificationsTable.createdAt 으로 dedupe.
//   - 평일에만 실행 (토/일 KST 는 발송 안 함).
//   - 출퇴근 attendance.status 가 "absent"/"leave"/"business_trip" 이면 그날은
//     결근·연차·출장 로 보고 발송 생략. (단순 지각/조퇴는 면제 대상이 아니다)
//   - 사용자가 본인 토글(users.dailyJournalReminderEnabled=false) 을 끄면 발송 생략.
//   - 본사 관리자는 platform_settings 의 발송 시각을 바꿀 수 있다 (HH:MM 24h).
//
// 발송 시각 키 / 기본값:
//   daily_journal_reminder_evening_at = "18:00"  (그 시각 이후 첫 tick 에서 평가)
//   daily_journal_reminder_morning_at = "09:30"  (그 시각 이후 첫 tick 에서 평가)

const REMINDER_TARGET_ROLES = ["manager", "accountant", "facility_staff"] as const;
const REMINDER_EVENING_KEY = "daily_journal_reminder_evening_at";
const REMINDER_MORNING_KEY = "daily_journal_reminder_morning_at";
const REMINDER_DEFAULT_EVENING = "18:00";
const REMINDER_DEFAULT_MORNING = "09:30";

function pad2(n: number): string {
  return n < 10 ? `0${n}` : String(n);
}

function kstNow(): Date {
  // UTC + 9h. Date 객체의 UTC getter 들을 써서 "KST 의 시·분·요일·일자" 를 읽는다.
  return new Date(Date.now() + 9 * 60 * 60 * 1000);
}

function kstYmd(d: Date): string {
  return `${d.getUTCFullYear()}-${pad2(d.getUTCMonth() + 1)}-${pad2(d.getUTCDate())}`;
}

function kstAddDays(ymd: string, delta: number): string {
  const [y, m, d] = ymd.split("-").map(Number);
  const t = Date.UTC(y, m - 1, d) + delta * 24 * 60 * 60 * 1000;
  const dt = new Date(t);
  return `${dt.getUTCFullYear()}-${pad2(dt.getUTCMonth() + 1)}-${pad2(dt.getUTCDate())}`;
}

function startOfTodayKstAsUtc(): Date {
  // KST 자정의 UTC 표현 = (KST 현재의 자정) - 9h.
  const k = kstNow();
  const midnightKstAsUtcMs = Date.UTC(
    k.getUTCFullYear(), k.getUTCMonth(), k.getUTCDate(), 0, 0, 0, 0
  ) - 9 * 60 * 60 * 1000;
  return new Date(midnightKstAsUtcMs);
}

function parseHHmm(value: string | null | undefined, fallback: string): { h: number; m: number; raw: string } {
  const raw = (value && /^\d{1,2}:\d{2}$/.test(value)) ? value : fallback;
  const [hh, mm] = raw.split(":").map(Number);
  const h = Math.min(23, Math.max(0, hh));
  const m = Math.min(59, Math.max(0, mm));
  return { h, m, raw: `${pad2(h)}:${pad2(m)}` };
}

async function getReminderSetting(key: string, fallback: string): Promise<{ h: number; m: number; raw: string }> {
  try {
    const [row] = await db
      .select({ value: platformSettingsTable.value })
      .from(platformSettingsTable)
      .where(eq(platformSettingsTable.key, key));
    return parseHHmm(row?.value, fallback);
  } catch {
    return parseHHmm(undefined, fallback);
  }
}

interface ReminderTargetUser {
  id: number;
  name: string;
  role: string;
  buildingId: number | null;
}

async function loadReminderTargets(): Promise<ReminderTargetUser[]> {
  const rows = await db
    .select({
      id: usersTable.id,
      name: usersTable.name,
      role: usersTable.role,
      buildingId: usersTable.buildingId,
      enabled: usersTable.dailyJournalReminderEnabled,
      approval: usersTable.approvalStatus,
    })
    .from(usersTable)
    .where(inArray(usersTable.role, [...REMINDER_TARGET_ROLES]));
  return rows
    .filter((r) => r.enabled !== false)
    .filter((r) => r.approval !== "rejected")
    .filter((r) => typeof r.buildingId === "number")
    .map((r) => ({ id: r.id, name: r.name, role: r.role, buildingId: r.buildingId ?? null }));
}

interface RunReminderArgs {
  notificationType: "daily_journal_reminder_evening" | "daily_journal_reminder_morning";
  targetDate: string;       // 일보가 있어야 하는 날짜 (YYYY-MM-DD KST)
  buildTitle: () => string;
  buildMessage: (user: ReminderTargetUser) => string;
}

async function runDailyJournalReminderPass(args: RunReminderArgs): Promise<number> {
  const sinceUtc = startOfTodayKstAsUtc();
  const targets = await loadReminderTargets();
  if (targets.length === 0) return 0;

  // 1) 오늘(=now KST) 안에 같은 type 으로 이미 발송된 user 목록.
  const alreadySent = await db
    .select({ recipient: notificationsTable.recipientType })
    .from(notificationsTable)
    .where(
      and(
        eq(notificationsTable.notificationType, args.notificationType),
        gte(notificationsTable.createdAt, sinceUtc),
      ),
    );
  const sentUserIds = new Set<number>();
  for (const r of alreadySent) {
    const m = /^user:(\d+)$/.exec(r.recipient ?? "");
    if (m) sentUserIds.add(Number(m[1]));
  }

  // 2) targetDate 의 일보를 이미 가진 (building, role) 조합.
  const buildingIds = Array.from(new Set(targets.map((t) => t.buildingId).filter((b): b is number => typeof b === "number")));
  if (buildingIds.length === 0) return 0;
  const journals = await db
    .select({ buildingId: dailyJournalsTable.buildingId, role: dailyJournalsTable.role })
    .from(dailyJournalsTable)
    .where(
      and(
        inArray(dailyJournalsTable.buildingId, buildingIds),
        eq(dailyJournalsTable.journalDate, args.targetDate),
      ),
    );
  const haveJournal = new Set(journals.map((j) => `${j.buildingId}:${j.role}`));

  // 3) targetDate 출근 부재(결근/연차/출장) 사용자 → 발송 면제.
  const userIds = targets.map((t) => t.id);
  const attendanceRows = await db
    .select({ userId: attendanceTable.userId, status: attendanceTable.status })
    .from(attendanceTable)
    .where(
      and(
        inArray(attendanceTable.userId, userIds),
        eq(attendanceTable.checkDate, args.targetDate),
      ),
    );
  const exemptStatuses = new Set(["absent", "leave", "business_trip"]);
  const exemptUserIds = new Set<number>();
  for (const a of attendanceRows) {
    if (a.status && exemptStatuses.has(a.status)) exemptUserIds.add(a.userId);
  }

  let sent = 0;
  for (const u of targets) {
    if (sentUserIds.has(u.id)) continue;
    if (exemptUserIds.has(u.id)) continue;
    if (u.buildingId == null) continue;
    if (haveJournal.has(`${u.buildingId}:${u.role}`)) continue;

    await insertNotification({
      recipientType: `user:${u.id}`,
      notificationType: args.notificationType,
      title: args.buildTitle(),
      message: args.buildMessage(u),
      relatedEntityType: "daily_journal",
    });
    sent++;
  }
  return sent;
}

let lastEveningPassYmd: string | null = null;
let lastMorningPassYmd: string | null = null;

async function runDailyJournalReminderTick(): Promise<void> {
  const now = kstNow();
  const dow = now.getUTCDay(); // 0=일, 6=토 (KST 기준)
  // 사양: "평일에만 실행". 따라서 금요일 저녁 미작성자에게는 토요일 오전
  //   2차 리마인더가 가지 않는다 (의도된 동작 — 주말 알림 피로도 최소화).
  //   월요일 오전에도 일요일치 리마인더는 보내지 않는다 (대상이 토/일이라 평일 X).
  if (dow === 0 || dow === 6) return;

  const todayYmd = kstYmd(now);
  const yesterdayYmd = kstAddDays(todayYmd, -1);
  const nowMinutes = now.getUTCHours() * 60 + now.getUTCMinutes();

  const evening = await getReminderSetting(REMINDER_EVENING_KEY, REMINDER_DEFAULT_EVENING);
  const morning = await getReminderSetting(REMINDER_MORNING_KEY, REMINDER_DEFAULT_MORNING);

  // 저녁 패스: 오늘 KST 의 evening.h:evening.m 이후, 오늘 한 번만.
  if (lastEveningPassYmd !== todayYmd && nowMinutes >= evening.h * 60 + evening.m) {
    try {
      const n = await runDailyJournalReminderPass({
        notificationType: "daily_journal_reminder_evening",
        targetDate: todayYmd,
        buildTitle: () => "오늘 업무일지 한 번만 들여다볼까요?",
        buildMessage: () => `오늘(${todayYmd}) 업무일지가 아직 비어 있어요. 1분이면 충분합니다. 여기를 눌러 자동 작성을 시작해 보세요.`,
      });
      lastEveningPassYmd = todayYmd;
      if (n > 0) logger.info({ count: n, target: todayYmd }, "daily journal evening reminders sent");
    } catch (err) {
      logger.error({ err }, "daily journal evening reminder failed");
    }
  }

  // 오전 패스: 오늘 KST 의 morning.h:morning.m 이후, 오늘 한 번만. 어제 일보 대상.
  if (lastMorningPassYmd !== todayYmd && nowMinutes >= morning.h * 60 + morning.m) {
    try {
      const n = await runDailyJournalReminderPass({
        notificationType: "daily_journal_reminder_morning",
        targetDate: yesterdayYmd,
        buildTitle: () => "어제 업무일지를 마무리해 볼까요?",
        buildMessage: () => `어제(${yesterdayYmd}) 업무일지가 비어 있어요. 지난 날짜로 지금도 작성하실 수 있어요. 여기를 눌러 마무리해 주세요.`,
      });
      lastMorningPassYmd = todayYmd;
      if (n > 0) logger.info({ count: n, target: yesterdayYmd }, "daily journal morning reminders sent");
    } catch (err) {
      logger.error({ err }, "daily journal morning reminder failed");
    }
  }
}

// [Task #793] 분할부과 스케줄 월별 회차 인식.
//   active 상태인 expense_voucher_schedules 의 currentRound 를 현재 월에 맞춰 한 회차씩
//   진행시키며, 진행할 때마다 voucher_schedule.tick 을 발행한다. 회계엔진(T6) 구독자가
//   `(차) 5100 관리비용 / (대) 1200 선급비용` 분개를 자동 생성한다.
//
//   멱등성: currentRound 갱신은 CAS(WHERE current_round = oldVal) 로 처리. 동일 월에
//   여러 번 실행되어도 expectedRound 까지만 진행되므로 중복 분개가 발생하지 않는다.
//   마지막 회차의 monthlyAmount 는 totalAmount - monthlyAmount * (months-1) 로 보정해
//   선급비용 잔액이 정확히 0 이 되도록 한다.
export async function runVoucherScheduleMonthlyTick(now: Date = new Date()): Promise<{ advanced: number }> {
  const currentMonth = `${now.getUTCFullYear()}-${String(now.getUTCMonth() + 1).padStart(2, "0")}`;
  const actives = await db
    .select()
    .from(expenseVoucherSchedulesTable)
    .where(eq(expenseVoucherSchedulesTable.status, "active"));
  let advanced = 0;
  for (const s of actives) {
    const expected = expectedRound(s.startMonth, currentMonth, s.months);
    let cur = s.currentRound;
    while (cur < expected) {
      const next = cur + 1;
      const isFinal = next === s.months;
      const amount = computeRoundAmount(next, s.months, s.totalAmount, s.monthlyAmount);
      const newStatus = isFinal ? "completed" : "active";
      const [updated] = await db
        .update(expenseVoucherSchedulesTable)
        .set({ currentRound: next, status: newStatus })
        .where(and(
          eq(expenseVoucherSchedulesTable.id, s.id),
          eq(expenseVoucherSchedulesTable.currentRound, cur),
        ))
        .returning({ id: expenseVoucherSchedulesTable.id });
      if (!updated) break; // 다른 워커가 선점 — 다음 schedule 로
      const tickMonth = addMonths(s.startMonth, next - 1);
      publishScheduleTick({
        scheduleId: s.id,
        voucherId: s.voucherId,
        buildingId: s.buildingId ?? null,
        month: tickMonth,
        round: next,
        totalRounds: s.months,
        monthlyAmount: amount,
        reason: isFinal ? "completed" : "near_end",
      });
      advanced += 1;
      cur = next;
    }
  }
  if (advanced > 0) logger.info({ advanced, currentMonth }, "[Task #793] voucher schedule monthly ticks advanced");
  return { advanced };
}

let dailyTimer: ReturnType<typeof setInterval> | null = null;
let monthlyTimer: ReturnType<typeof setInterval> | null = null;
let reminderTimer: ReturnType<typeof setInterval> | null = null;
// [Task #781] 외부 발송 워커 타이머 — 1분 간격으로 due 잡 처리.
let dispatchTimer: ReturnType<typeof setInterval> | null = null;

export function startScheduler(): void {
  logger.info("Starting automated scheduler for privacy and vehicle tasks");

  runPrivacyDestructionAlerts().catch((err) => logger.error({ err }, "Scheduled privacy alert failed"));
  runPrivacyDestructionProcessing().catch((err) => logger.error({ err }, "Scheduled privacy destruction failed"));
  runVoucherScheduleMonthlyTick().catch((err) => logger.error({ err }, "[Task #793] voucher schedule monthly tick failed"));
  autoGenerateDraftsForUpcoming().catch((err) => logger.error({ err }, "Scheduled draft/RFQ automation failed"));
  runWeeklyReportAutoGeneration().catch((err) => logger.error({ err }, "Scheduled weekly report failed"));
  runDelinquencyDetection().catch((err) => logger.error({ err }, "Scheduled delinquency detection failed"));
  runDelinquencyAutoResolution().catch((err) => logger.error({ err }, "Scheduled delinquency auto-resolution failed"));
  runNoticePostingSuggestion().catch((err) => logger.error({ err }, "Scheduled notice posting suggestion failed"));
  // [Task #226] 미열람 견적 일부 환불 (기본 7일 이상 미열람 시 60% 환불).
  refundUnviewedQuotes()
    .then((r) => { if (r.refundedCount > 0) logger.info(r, "Unviewed-quote refund job processed"); })
    .catch((err) => logger.error({ err }, "Unviewed-quote refund job failed"));

  const now = new Date();
  if (now.getDate() === 1) {
    runVehicleMonthlyInspection().catch((err) => logger.error({ err }, "Scheduled vehicle inspection failed"));
  }
  if (now.getDay() === 1 && now.getDate() <= 7) {
    runMonthlyReportAutoGeneration().catch((err) => logger.error({ err }, "Scheduled monthly report failed"));
  }

  dailyTimer = setInterval(async () => {
    logger.info("Running daily scheduled tasks");
    try {
      await runPrivacyDestructionAlerts();
      await runPrivacyDestructionProcessing();
      await runVoucherScheduleMonthlyTick();
      await autoGenerateDraftsForUpcoming();
      await runWeeklyReportAutoGeneration();
      await runMonthlyReportAutoGeneration();
      await runDelinquencyDetection();
      await runDelinquencyAutoResolution();
      await runNoticePostingSuggestion();
      await refundUnviewedQuotes();
      // [Task #296] usage_events 보존 정책: 180일 이전 이벤트 자동 정리.
      const purged = await purgeOldUsageEvents(180);
      if (purged > 0) logger.info({ purged }, "Purged old usage_events rows");
    } catch (err) {
      logger.error({ err }, "Daily scheduled task failed");
    }
  }, 24 * 60 * 60 * 1000);

  monthlyTimer = setInterval(async () => {
    const currentDate = new Date();
    if (currentDate.getDate() === 1) {
      logger.info("Running monthly vehicle inspection (1st of month)");
      try {
        await runVehicleMonthlyInspection();
      } catch (err) {
        logger.error({ err }, "Monthly vehicle inspection failed");
      }
    }
  }, 24 * 60 * 60 * 1000);

  // [Task #609] 일보 작성 독려: 15분 간격으로 평가하며, 설정된 발송 시각을
  //   넘겼고 오늘 아직 발송 안 했으면 한 번 발송. 평일/본인 토글/결근/중복 모두 내부에서 체크.
  runDailyJournalReminderTick().catch((err) => logger.error({ err }, "Daily journal reminder tick failed"));
  reminderTimer = setInterval(() => {
    runDailyJournalReminderTick().catch((err) => logger.error({ err }, "Daily journal reminder tick failed"));
  }, 15 * 60 * 1000);

  // [Task #781] 외부 발송 잡 큐 워커 — 1분 간격. due(scheduledAt<=now) 인 queued/failed 잡을 처리.
  dispatchTimer = setInterval(() => {
    processDueJobs(50).catch((err) => logger.error({ err }, "Dispatch worker tick failed"));
  }, 60 * 1000);
}

export function stopScheduler(): void {
  if (dailyTimer) {
    clearInterval(dailyTimer);
    dailyTimer = null;
  }
  if (monthlyTimer) {
    clearInterval(monthlyTimer);
    monthlyTimer = null;
  }
  if (reminderTimer) {
    clearInterval(reminderTimer);
    reminderTimer = null;
  }
  if (dispatchTimer) {
    clearInterval(dispatchTimer);
    dispatchTimer = null;
  }
  logger.info("Scheduler stopped");
}
