import { eq, and, lte, gte, isNotNull, sql, desc, ne } from "drizzle-orm";
import { db, tenantsTable, ownersTable, dataDestructionLogsTable, notificationsTable, vehiclesTable, vehicleHistoryTable, dailyReportsTable, weeklySummaryReportsTable, monthlySummaryReportsTable, inspectionsTable, inspectionLogsTable, unitsTable, delinquencyActionsTable, monthlyPaymentsTable } from "@workspace/db";
import { logger } from "./lib/logger";
import { autoGenerateDraftsForUpcoming } from "./routes/dashboard";

function getToday(): string {
  return new Date().toISOString().split("T")[0];
}

async function runPrivacyDestructionAlerts(): Promise<void> {
  const todayStr = getToday();
  const thirtyDaysLater = new Date();
  thirtyDaysLater.setDate(thirtyDaysLater.getDate() + 30);
  const thirtyDaysStr = thirtyDaysLater.toISOString().split("T")[0];

  const existingAlerts = await db
    .select()
    .from(notificationsTable)
    .where(
      and(
        eq(notificationsTable.notificationType, "data_destruction_alert"),
        gte(notificationsTable.createdAt, new Date(todayStr))
      )
    );

  if (existingAlerts.length > 0) {
    logger.info("Privacy destruction alert already sent today, skipping");
    return;
  }

  const upcomingTenants = await db
    .select()
    .from(tenantsTable)
    .where(
      and(
        isNotNull(tenantsTable.dataDestructionDate),
        lte(tenantsTable.dataDestructionDate, thirtyDaysStr),
        sql`${tenantsTable.dataDestructionDate} > ${todayStr}`,
        eq(tenantsTable.status, "moved_out")
      )
    );

  const upcomingOwners = await db
    .select()
    .from(ownersTable)
    .where(
      and(
        isNotNull(ownersTable.dataDestructionDate),
        lte(ownersTable.dataDestructionDate, thirtyDaysStr),
        sql`${ownersTable.dataDestructionDate} > ${todayStr}`,
        eq(ownersTable.status, "moved_out")
      )
    );

  const totalCount = upcomingTenants.length + upcomingOwners.length;

  if (totalCount > 0) {
    const details = [
      ...upcomingTenants.map((t) => `입주자 ${t.unit}호 ${t.tenantName} (${t.dataDestructionDate})`),
      ...upcomingOwners.map((o) => `소유자 ${o.unit}호 ${o.ownerName} (${o.dataDestructionDate})`),
    ].join(", ");

    await db.insert(notificationsTable).values({
      recipientType: "admin",
      notificationType: "data_destruction_alert",
      title: "개인정보 파기 예정 알림",
      message: `30일 이내 파기 예정: ${totalCount}건 - ${details}`,
      relatedEntityType: "privacy",
    });

    logger.info({ count: totalCount }, "Privacy destruction alert created");
  }
}

async function runPrivacyDestructionProcessing(): Promise<void> {
  const todayStr = getToday();

  const dueTenants = await db
    .select()
    .from(tenantsTable)
    .where(
      and(
        isNotNull(tenantsTable.dataDestructionDate),
        lte(tenantsTable.dataDestructionDate, todayStr),
        eq(tenantsTable.status, "moved_out")
      )
    );

  const dueOwners = await db
    .select()
    .from(ownersTable)
    .where(
      and(
        isNotNull(ownersTable.dataDestructionDate),
        lte(ownersTable.dataDestructionDate, todayStr),
        eq(ownersTable.status, "moved_out")
      )
    );

  let processedCount = 0;

  for (const tenant of dueTenants) {
    await db.insert(dataDestructionLogsTable).values({
      entityType: "tenant",
      entityId: tenant.id,
      unit: tenant.unit,
      originalName: tenant.tenantName,
      destructionType: "anonymization",
      processedBy: "system",
      notes: `자동 파기 - 퇴거일: ${tenant.moveOutDate}, 파기예정일: ${tenant.dataDestructionDate}`,
    });

    await db
      .update(tenantsTable)
      .set({
        tenantName: "***",
        residentId: null,
        phone: null,
        emergencyContact: null,
        email: null,
        registeredAddress: null,
        guarantorName: null,
        guarantorPhone: null,
        guarantorRelation: null,
        notes: "[개인정보 자동 파기 처리됨]",
        status: "destroyed",
      })
      .where(eq(tenantsTable.id, tenant.id));

    processedCount++;
  }

  for (const owner of dueOwners) {
    await db.insert(dataDestructionLogsTable).values({
      entityType: "owner",
      entityId: owner.id,
      unit: owner.unit,
      originalName: owner.ownerName,
      destructionType: "anonymization",
      processedBy: "system",
      notes: `자동 파기 - 퇴거일: ${owner.moveOutDate}, 파기예정일: ${owner.dataDestructionDate}`,
    });

    await db
      .update(ownersTable)
      .set({
        ownerName: "***",
        phone: null,
        email: null,
        registeredAddress: null,
        notes: "[개인정보 자동 파기 처리됨]",
        status: "destroyed",
      })
      .where(eq(ownersTable.id, owner.id));

    processedCount++;
  }

  if (processedCount > 0) {
    await db.insert(notificationsTable).values({
      recipientType: "admin",
      notificationType: "data_destruction_completed",
      title: "개인정보 자동 파기 처리 완료",
      message: `${processedCount}건의 개인정보가 자동 파기(익명화) 처리되었습니다.`,
      relatedEntityType: "privacy",
    });

    logger.info({ count: processedCount }, "Privacy data auto-destroyed");
  }
}

async function runVehicleMonthlyInspection(): Promise<void> {
  const now = new Date();
  const monthStart = new Date(now.getFullYear(), now.getMonth(), 1);

  const existingInspection = await db
    .select()
    .from(notificationsTable)
    .where(
      and(
        eq(notificationsTable.notificationType, "vehicle_monthly_inspection"),
        gte(notificationsTable.createdAt, monthStart)
      )
    );

  if (existingInspection.length > 0) {
    logger.info("Vehicle monthly inspection already run this month, skipping");
    return;
  }

  const allVehicles = await db
    .select()
    .from(vehiclesTable)
    .where(eq(vehiclesTable.status, "registered"));

  const registeredUnits = new Set(allVehicles.map((v) => v.unit));

  const allTenants = await db
    .select({ unit: tenantsTable.unit, tenantName: tenantsTable.tenantName })
    .from(tenantsTable)
    .where(eq(tenantsTable.status, "active"));

  const unregisteredUnits = allTenants.filter((t) => !registeredUnits.has(t.unit));

  if (unregisteredUnits.length > 0) {
    const unitList = unregisteredUnits
      .slice(0, 10)
      .map((u) => `${u.unit}호`)
      .join(", ");
    const suffix = unregisteredUnits.length > 10 ? ` 외 ${unregisteredUnits.length - 10}건` : "";

    await db.insert(notificationsTable).values({
      recipientType: "admin",
      notificationType: "vehicle_monthly_inspection",
      title: "월별 차량 점검 알림",
      message: `미등록 차량 ${unregisteredUnits.length}건 확인 필요: ${unitList}${suffix}`,
      relatedEntityType: "vehicle",
    });

    logger.info({ count: unregisteredUnits.length }, "Vehicle monthly inspection alert created");
  }
}

async function runWeeklyReportAutoGeneration(): Promise<void> {
  const today = new Date();
  const dayOfWeek = today.getDay();
  if (dayOfWeek !== 1) return;

  const mondayStr = today.toISOString().split("T")[0];
  const lastSunday = new Date(today);
  lastSunday.setDate(today.getDate() - 1);
  const lastSundayStr = lastSunday.toISOString().split("T")[0];
  const lastMonday = new Date(today);
  lastMonday.setDate(today.getDate() - 7);
  const lastMondayStr = lastMonday.toISOString().split("T")[0];

  const existing = await db.select().from(weeklySummaryReportsTable)
    .where(eq(weeklySummaryReportsTable.weekStart, lastMondayStr));
  if (existing.length > 0) {
    logger.info("Weekly report already exists for this week, skipping");
    return;
  }

  const dailyReports = await db.select().from(dailyReportsTable)
    .where(and(
      gte(dailyReportsTable.reportDate, lastMondayStr),
      lte(dailyReportsTable.reportDate, lastSundayStr)
    ));

  const typeLabel: Record<string, string> = {
    expense: "경비", cleaning: "미화", maintenance: "유지보수",
    security: "보안", other: "기타",
  };
  const typeCount: Record<string, number> = {};
  for (const dr of dailyReports) {
    const label = typeLabel[dr.reportType] || dr.reportType;
    typeCount[label] = (typeCount[label] || 0) + 1;
  }

  const allInspections = await db.select().from(inspectionsTable);
  const weekInspDue = allInspections.filter(
    (i) => i.nextDueDate >= lastMondayStr && i.nextDueDate <= lastSundayStr
  );
  const allLogs = await db.select().from(inspectionLogsTable);
  const weekLogs = allLogs.filter(
    (l) => l.inspectionDate >= lastMondayStr && l.inspectionDate <= lastSundayStr
  );

  let inspSection = "";
  if (weekInspDue.length > 0 || weekLogs.length > 0) {
    inspSection = "\n\n■ 금주 점검 현황";
    if (weekLogs.length > 0) {
      inspSection += `\n  완료된 점검: ${weekLogs.length}건`;
    }
    const pending = weekInspDue.filter(
      (i) => !weekLogs.some((l) => l.inspectionId === i.id)
    );
    if (pending.length > 0) {
      inspSection += `\n  미완료 점검: ${pending.length}건`;
    }
  }

  const summary = `[자동 생성] 주간 보고 요약 (${lastMondayStr} ~ ${lastSundayStr})\n\n총 ${dailyReports.length}건의 일간 보고서\n${Object.entries(typeCount).map(([t, c]) => `${t}: ${c}건`).join("\n")}\n\n${dailyReports.map((dr) => `- [${dr.reportDate}] ${dr.title}`).join("\n")}${inspSection}`;

  await db.insert(weeklySummaryReportsTable).values({
    title: `[자동] ${lastMondayStr} 주간 보고`,
    weekStart: lastMondayStr,
    weekEnd: lastSundayStr,
    summary,
    totalDailyReports: dailyReports.length,
    dailyReportIds: dailyReports.map((d) => d.id).join(","),
    authorId: 0,
    authorName: "시스템",
    status: "draft",
  });

  logger.info({ weekStart: lastMondayStr, dailyCount: dailyReports.length }, "Auto-generated weekly report");
}

async function runMonthlyReportAutoGeneration(): Promise<void> {
  const today = new Date();
  const dayOfWeek = today.getDay();
  if (dayOfWeek !== 1 || today.getDate() > 7) return;

  const lastMonth = new Date(today.getFullYear(), today.getMonth() - 1, 1);
  const reportMonth = `${lastMonth.getFullYear()}-${String(lastMonth.getMonth() + 1).padStart(2, "0")}`;

  const existing = await db.select().from(monthlySummaryReportsTable)
    .where(eq(monthlySummaryReportsTable.reportMonth, reportMonth));
  if (existing.length > 0) {
    logger.info("Monthly report already exists for this month, skipping");
    return;
  }

  const weeklyReports = await db.select().from(weeklySummaryReportsTable)
    .where(sql`${weeklySummaryReportsTable.weekStart} LIKE ${reportMonth + "%"}`);

  const totalDailyCount = weeklyReports.reduce((s, r) => s + r.totalDailyReports, 0);

  const monthStart = `${reportMonth}-01`;
  const monthEndDate = new Date(parseInt(reportMonth.split("-")[0]), parseInt(reportMonth.split("-")[1]), 0);
  const monthEnd = monthEndDate.toISOString().split("T")[0];

  const allLogs = await db.select().from(inspectionLogsTable);
  const monthLogs = allLogs.filter(
    (l) => l.inspectionDate >= monthStart && l.inspectionDate <= monthEnd
  );

  let inspSummary = "";
  if (monthLogs.length > 0) {
    const resultCounts: Record<string, number> = {};
    for (const l of monthLogs) {
      resultCounts[l.result] = (resultCounts[l.result] || 0) + 1;
    }
    inspSummary = `\n\n■ 월간 점검 현황\n  완료: ${monthLogs.length}건\n  결과: ${Object.entries(resultCounts).map(([r, c]) => `${r} ${c}건`).join(", ")}`;
  }

  const summary = `[자동 생성] 월간 보고 요약 (${reportMonth})\n\n총 ${weeklyReports.length}건의 주간 보고서\n총 ${totalDailyCount}건의 일간 보고서 집계\n\n${weeklyReports.map((wr) => `- ${wr.title} (일간 보고 ${wr.totalDailyReports}건)`).join("\n")}${inspSummary}`;

  await db.insert(monthlySummaryReportsTable).values({
    title: `[자동] ${reportMonth} 월간 보고`,
    reportMonth,
    summary,
    totalWeeklyReports: weeklyReports.length,
    weeklyReportIds: weeklyReports.map((w) => w.id).join(","),
    authorId: 0,
    authorName: "시스템",
    status: "draft",
  });

  logger.info({ reportMonth, weeklyCount: weeklyReports.length }, "Auto-generated monthly report");
}

async function computeUnitBillingStatus(unitId: number): Promise<{ overdueMonths: number; totalOverdueAmount: number } | null> {
  const now = new Date();
  const cutoffDate = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-25`;

  const unpaidRecords = await db.select().from(monthlyPaymentsTable)
    .where(
      and(
        eq(monthlyPaymentsTable.unitId, unitId),
        eq(monthlyPaymentsTable.isPaid, false),
        lte(monthlyPaymentsTable.dueDate, cutoffDate)
      )
    );

  if (unpaidRecords.length < 2) return null;

  const totalOverdueAmount = unpaidRecords.reduce((sum, r) => sum + (r.totalAmount - r.paidAmount), 0);

  return {
    overdueMonths: unpaidRecords.length,
    totalOverdueAmount: Math.round(totalOverdueAmount),
  };
}

async function runDelinquencyDetection(): Promise<void> {
  const todayStr = getToday();

  const existingCheck = await db
    .select()
    .from(notificationsTable)
    .where(
      and(
        eq(notificationsTable.notificationType, "delinquency_detection"),
        gte(notificationsTable.createdAt, new Date(todayStr))
      )
    );

  if (existingCheck.length > 0) {
    logger.info("Delinquency detection already run today, skipping");
    return;
  }

  const allUnits = await db.select().from(unitsTable)
    .where(eq(unitsTable.status, "occupied"));

  if (allUnits.length === 0) return;

  const allTenants = await db.select().from(tenantsTable)
    .where(eq(tenantsTable.status, "active"));

  const tenantByUnit = new Map<number, typeof allTenants[0]>();
  for (const t of allTenants) {
    if (t.unitId) tenantByUnit.set(t.unitId, t);
  }

  const existingActive = await db.select().from(delinquencyActionsTable)
    .where(eq(delinquencyActionsTable.status, "active"));
  const activeUnitIds = new Set(existingActive.map(a => a.unitId));

  let detectedCount = 0;

  for (const unit of allUnits) {
    if (activeUnitIds.has(unit.id)) continue;

    const billing = await computeUnitBillingStatus(unit.id);
    if (!billing) continue;

    const tenant = tenantByUnit.get(unit.id);

    await db.insert(delinquencyActionsTable).values({
      unitId: unit.id,
      unitNumber: unit.unitNumber,
      tenantId: tenant?.id ?? null,
      tenantName: tenant?.tenantName ?? null,
      overdueMonths: billing.overdueMonths,
      totalOverdueAmount: billing.totalOverdueAmount,
      actionType: "detected",
      status: "active",
      performedBy: "system",
      notes: `[${todayStr}] 자동 감지: ${billing.overdueMonths}개월 연체, 미납액 ${billing.totalOverdueAmount.toLocaleString()}원`,
    });

    detectedCount++;
  }

  if (detectedCount > 0) {
    await db.insert(notificationsTable).values({
      recipientType: "admin",
      notificationType: "delinquency_detection",
      title: "연체 세대 자동 감지",
      message: `${detectedCount}건의 2개월 이상 연체 세대가 감지되었습니다. 연체 관리에서 확인하세요.`,
      relatedEntityType: "delinquency",
    });

    logger.info({ count: detectedCount }, "Delinquency detection completed");
  }
}

async function runDelinquencyAutoResolution(): Promise<void> {
  const todayStr = getToday();

  const activeActions = await db.select().from(delinquencyActionsTable)
    .where(eq(delinquencyActionsTable.status, "active"));

  if (activeActions.length === 0) return;

  let resolvedCount = 0;

  for (const action of activeActions) {
    if (!action.unitId) continue;

    const [unit] = await db.select().from(unitsTable)
      .where(eq(unitsTable.id, action.unitId));
    if (!unit) continue;

    const billing = await computeUnitBillingStatus(unit.id);

    if (billing) continue;

    if (action.actionType === "parking_suspended") {
      const suspendedVehicles = await db.select().from(vehiclesTable)
        .where(and(
          eq(vehiclesTable.unit, action.unitNumber),
          eq(vehiclesTable.buildingId, unit.buildingId),
          eq(vehiclesTable.status, "suspended")
        ));

      for (const v of suspendedVehicles) {
        await db.update(vehiclesTable)
          .set({ status: "registered" })
          .where(eq(vehiclesTable.id, v.id));

        await db.insert(vehicleHistoryTable).values({
          vehicleId: v.id,
          action: "reactivated",
          vehicleNumber: v.vehicleNumber,
          unit: v.unit,
          performedBy: "system",
          notes: "연체 해소 자동 감지로 주차권 복원",
        });
      }
    }

    await db.update(delinquencyActionsTable)
      .set({
        status: "resolved",
        resolvedDate: new Date(),
        notes: `${action.notes ? action.notes + "\n" : ""}[${todayStr}] 자동 해소: 미납 해소 감지`,
      })
      .where(eq(delinquencyActionsTable.id, action.id));

    resolvedCount++;
  }

  if (resolvedCount > 0) {
    await db.insert(notificationsTable).values({
      recipientType: "admin",
      notificationType: "delinquency_auto_resolved",
      title: "연체 자동 해소",
      message: `${resolvedCount}건의 연체가 수납 확인으로 자동 해소되었습니다.`,
      relatedEntityType: "delinquency",
    });

    logger.info({ count: resolvedCount }, "Delinquency auto-resolution completed");
  }
}

let dailyTimer: ReturnType<typeof setInterval> | null = null;
let monthlyTimer: ReturnType<typeof setInterval> | null = null;

export function startScheduler(): void {
  logger.info("Starting automated scheduler for privacy and vehicle tasks");

  runPrivacyDestructionAlerts().catch((err) => logger.error({ err }, "Scheduled privacy alert failed"));
  runPrivacyDestructionProcessing().catch((err) => logger.error({ err }, "Scheduled privacy destruction failed"));
  autoGenerateDraftsForUpcoming().catch((err) => logger.error({ err }, "Scheduled draft/RFQ automation failed"));
  runWeeklyReportAutoGeneration().catch((err) => logger.error({ err }, "Scheduled weekly report failed"));
  runDelinquencyDetection().catch((err) => logger.error({ err }, "Scheduled delinquency detection failed"));
  runDelinquencyAutoResolution().catch((err) => logger.error({ err }, "Scheduled delinquency auto-resolution failed"));

  const now = new Date();
  if (now.getDate() === 1) {
    runVehicleMonthlyInspection().catch((err) => logger.error({ err }, "Scheduled vehicle inspection failed"));
  }
  if (now.getDay() === 1 && now.getDate() <= 7) {
    runMonthlyReportAutoGeneration().catch((err) => logger.error({ err }, "Scheduled monthly report failed"));
  }

  dailyTimer = setInterval(async () => {
    logger.info("Running daily scheduled tasks");
    try {
      await runPrivacyDestructionAlerts();
      await runPrivacyDestructionProcessing();
      await autoGenerateDraftsForUpcoming();
      await runWeeklyReportAutoGeneration();
      await runMonthlyReportAutoGeneration();
      await runDelinquencyDetection();
      await runDelinquencyAutoResolution();
    } catch (err) {
      logger.error({ err }, "Daily scheduled task failed");
    }
  }, 24 * 60 * 60 * 1000);

  monthlyTimer = setInterval(async () => {
    const currentDate = new Date();
    if (currentDate.getDate() === 1) {
      logger.info("Running monthly vehicle inspection (1st of month)");
      try {
        await runVehicleMonthlyInspection();
      } catch (err) {
        logger.error({ err }, "Monthly vehicle inspection failed");
      }
    }
  }, 24 * 60 * 60 * 1000);
}

export function stopScheduler(): void {
  if (dailyTimer) {
    clearInterval(dailyTimer);
    dailyTimer = null;
  }
  if (monthlyTimer) {
    clearInterval(monthlyTimer);
    monthlyTimer = null;
  }
  logger.info("Scheduler stopped");
}
